# An example

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[An example](https://numpy.org/doc/1.17/user/quickstart.html#an-example)

The more important attributes of an ndarray object are:
* **ndarray.ndim**  
  the number of axes (dimensions) of the array
* **ndarray.shape**  
  the dimensions of the array
* **ndarray.size**  
  the total number of elements of the array
* **ndarray.dtype**  
  an object describing the type of the elements in the array
* **ndarray.itemsize**  
  the size in bytes of each element of the array

In [1]:
import numpy as np

In [4]:
# create 1d ndarray

x = np.arange(1, 12 + 1)

print(
    f'{type(a)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    f'dtype: {x.dtype}',
    f'itemsize: {x.itemsize}',
    sep='\n')

<class 'numpy.ndarray'>:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12
dtype: int64
itemsize: 8


In [5]:
# reshape 1d ndarray
# to 2d

x = x.reshape((3, 4))

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    f'dtype: {x.dtype}',
    f'itemsize: {x.itemsize}',
    sep='\n')

<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8
