# The basics

## An example

The more important attributes of an `ndarray` object are:
- `ndarray.ndim`  
  the number of axes (dimensions) of the array,
- `ndarray.shape`  
  the dimension of the array,
- `ndarray.size`  
  the total number of elements of the array,
- `ndarray.dtype`  
  an object describing the type of the elements in the array,
- `ndarray.itemsize`  
  the size in bytes of each element of the array.
- `ndarray.data`  
  the buffer containing the actual elements of the array.

In [1]:
import numpy as np

In [2]:
# Creates 1D array. 
x = np.arange(1, 12 + 1)

print(f'{type(x)}: {x}',
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      f'itemsize: {x.itemsize}',
      sep='\n')

<class 'numpy.ndarray'>: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12
dtype: int64
itemsize: 8


In [3]:
# Applies a list comprehension
# to extract elements from a buffer of 1D array.
y = x.data
z = [_ for _ in y]

print(f'{type(y)}: {y}',
      f'{type(z)}: {z}',
      sep='\n')

<class 'memoryview'>: <memory at 0x7f2f0aef4c40>
<class 'list'>: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [4]:
# Reshapes 1D array, making 2D one. 
x = x.reshape(3, 4)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      f'itemsize: {x.itemsize}',
      sep='\n')

<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8


In [5]:
# Reshapes 2D array, making 3D one.
x = x.reshape(2, 2, 3)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      f'itemsize: {x.itemsize}',
      sep='\n')

<class 'numpy.ndarray'>:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)
size: 12
dtype: int64
itemsize: 8
