# Array Creation

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Array Creation](https://numpy.org/doc/1.17/user/quickstart.html#array-creation)

You can create an array 
from a regular Python list or tuple 
using the **array** function.

The type of the array 
can also be explicitly specified 
at creation time.

In [2]:
import numpy as np

In [20]:
# create 1d array
# from list

n = 12
x = [i + 1 for i in range(0, n)]
y = np.array(x)

print(
    f'{type(x)}:', x,
    f'{type(y)}:', y,
    f'ndim: {y.ndim}',
    f'shape: {y.shape}',
    f'size: {y.size}',
    f'dtype: {y.dtype}',
    f'itemsize: {y.itemsize}',
    sep='\n')

<class 'list'>:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
<class 'numpy.ndarray'>:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12
dtype: int64
itemsize: 8


In [27]:
# create 2d array
# from list of lists

n, m = 3, 4
x = [[m * i + (j + 1) for j in range(0,  m)]
     for i in range(0, n)]
y = np.array(x)

print(
    f'{type(x)}:', x, '',
    f'{type(y)}:', y,
    f'ndim: {y.ndim}',
    f'shape: {y.shape}',
    f'size: {y.size}',
    f'dtype: {y.dtype}',
    f'itemsize: {y.itemsize}',
    sep='\n')

<class 'list'>:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8


In [26]:
# create 2d array
# from list of lists
# with specifieing dtype

n, m = 3, 4
x = [[m * i + (j + 1) for j in range(0,  m)]
     for i in range(0, n)]
y = np.array(x, dtype=float)

print(
    f'{type(x)}:', x, '',
    f'{type(y)}:', y,
    f'ndim: {y.ndim}',
    f'shape: {y.shape}',
    f'size: {y.size}',
    f'dtype: {y.dtype}',
    f'itemsize: {y.itemsize}',
    sep='\n')

<class 'list'>:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<class 'numpy.ndarray'>:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
ndim: 2
shape: (3, 4)
size: 12
dtype: float64
itemsize: 8
