# Array Creation

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Array Creation](https://numpy.org/doc/1.17/user/quickstart.html#array-creation)

NumPy offers several functions to create arrays
with initial placeholder content:
* **zeros** creates an array full of zeros,
* **ones** creates an array full of ones,
* **empty** creates an array
  whose initial content is random
  and depends on the state of the memory.

By default,
the dtype of the created array is float
but can also be specified.

In [2]:
import numpy as np

In [16]:
# create 1d array
# full of zeros
# with specifieing dtype

x = np.zeros(shape=12, dtype=int)

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    f'dtype: {x.dtype}',
    f'itemsize: {x.itemsize}',
    sep='\n')

<class 'numpy.ndarray'>:
[0 0 0 0 0 0 0 0 0 0 0 0]
ndim: 1
shape: (12,)
size: 12
dtype: int64
itemsize: 8


In [14]:
# create 2d array
# full of ones
# with specifieing dtype

x = np.ones(shape=(3, 4), dtype=int)

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    f'dtype: {x.dtype}',
    f'itemsize: {x.itemsize}',
    sep='\n')

<class 'numpy.ndarray'>:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8


In [17]:
# create 3d array
# full of randoms

x = np.empty((2, 3, 4))

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    f'dtype: {x.dtype}',
    f'itemsize: {x.itemsize}',
    sep='\n')

<class 'numpy.ndarray'>:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
ndim: 3
shape: (2, 3, 4)
size: 24
dtype: float64
itemsize: 8
