# Array Creation

## Functions to create

* NumPy offers several functions to create arrays
  with initial placeholder content:
  * **zeros** creates an array full of zeros,
  * **ones** creates an array full of ones,
  * **empty** creates an array
    whose initial content is random
    and depends on the state of the memory.
* By default, the dtype of the created array is float
  but can also be specified.

## Links

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Array Creation](https://numpy.org/doc/1.17/user/quickstart.html#array-creation)



In [1]:
import numpy as np


In [2]:
# Creates 1D ndarray full of zeros,
# using numpy.zeros function.
x = np.zeros(shape=12, dtype=int)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      f'itemsize: {x.itemsize}',
      sep='\n')


<class 'numpy.ndarray'>:
[0 0 0 0 0 0 0 0 0 0 0 0]
ndim: 1
shape: (12,)
size: 12
dtype: int64
itemsize: 8


In [3]:
# Creates 2D ndarray full of ones,
# using numpy.ones function.
x = np.ones(shape=(3, 4), dtype=int)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      f'itemsize: {x.itemsize}',
      sep='\n')


<class 'numpy.ndarray'>:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8


In [4]:
# Creates 3D ndarray full of randoms,
# using numpy.empty function.
x = np.empty((2, 3, 4))

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      f'itemsize: {x.itemsize}',
      sep='\n')


<class 'numpy.ndarray'>:
[[[ 4.64437661e-310  0.00000000e+000  6.91931441e-310 -8.24654890e-057]
  [ 6.91931444e-310  6.91931441e-310 -2.19677613e-281  6.91931444e-310]
  [ 6.91931441e-310  1.28868382e-047  6.91931441e-310  6.91931441e-310]]

 [[-1.40345622e-282  6.91931441e-310  6.91931441e-310  2.24346439e-191]
  [ 6.91931441e-310  6.91931441e-310  7.32016741e+026  6.91931441e-310]
  [ 6.91931441e-310 -2.20218395e-038  6.91931441e-310  6.91931441e-310]]]
ndim: 3
shape: (2, 3, 4)
size: 24
dtype: float64
itemsize: 8
