# Array Creation

## Create from list

- You can create an array from a regular Python list or tuple
  using the `array` function.
- The type of the array can also be explicitly specified
  at creation time.

In [1]:
import numpy as np

In [2]:
# Creates 1d array from a list.

n = 12
x = [i + 1 for i in range(0, n)]
y = np.array(x)

print(f'{type(x)}:', x,
      f'{type(y)}:', y,
      f'ndim: {y.ndim}',
      f'shape: {y.shape}',
      f'size: {y.size}',
      f'dtype: {y.dtype}',
      # f'itemsize: {y.itemsize}',
      sep='\n')

<class 'list'>:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
<class 'numpy.ndarray'>:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12
dtype: int64


In [3]:
# Creates 2d array from a list of lists.

n, m = 3, 4
x = [
    [m * i + (j + 1) for j in range(0,  m)]
    for i in range(0, n)
]
y = np.array(x)

print(f'{type(x)}:', x,
      f'{type(y)}:', y,
      f'ndim: {y.ndim}',
      f'shape: {y.shape}',
      f'size: {y.size}',
      f'dtype: {y.dtype}',
      # f'itemsize: {y.itemsize}',
      sep='\n')

<class 'list'>:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64


In [4]:
# Creates 2d array from a list of lists,
# specifying the type.

n, m = 3, 4
x = [
    [m * i + (j + 1) for j in range(0,  m)]
    for i in range(0, n)
]

y = np.array(
    x,
    # dtype=np.int8,
    # dtype=np.int16,
    # dtype=np.int32,
    # dtype=np.int64,
    # dtype=np.int,
    # dtype=int,
    
    # dtype=np.float16,
    # dtype=np.float32,
    # dtype=np.float64,
    # dtype=np.float,
    dtype=float,
    
    # dtype=np.complex64,
    # dtype=np.complex128,
    # dtype=np.complex,
)

print(f'{type(x)}:', x,
      f'{type(y)}:', y,
      f'ndim: {y.ndim}',
      f'shape: {y.shape}',
      f'size: {y.size}',
      f'dtype: {y.dtype}',
      # f'itemsize: {y.itemsize}',
      sep='\n')

<class 'list'>:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
<class 'numpy.ndarray'>:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
ndim: 2
shape: (3, 4)
size: 12
dtype: float64
