# The basics

## Array creation

### Functions to create

- NumPy offers several functions to create arrays
  with initial placeholder content:
  - `zeros` creates an array full of zeros,
  - `ones` creates an array full of ones,
  - `empty` creates an array
    whose initial content is random and
    depends on the state of the memory.
- By default, the type of the created array is `float`
  but can also be specified.

In [1]:
import numpy as np

In [2]:
# Create 1d array full of zeros,
# specifying necessary the shape and
# optionally the type.

x = np.zeros(shape=12, dtype=int)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      # f'itemsize: {x.itemsize}',
      sep='\n')

<class 'numpy.ndarray'>:
[0 0 0 0 0 0 0 0 0 0 0 0]
ndim: 1
shape: (12,)
size: 12
dtype: int64


In [3]:
# Creates 2d array full of ones,
# specifying necessary the shape and
# optionally the type.

x = np.ones(shape=(3, 4), dtype=int)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      # f'itemsize: {x.itemsize}',
      sep='\n')

<class 'numpy.ndarray'>:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64


In [4]:
# Creates 3d array full of randoms,
# specifying the shape.

x = np.empty((2, 3, 4))

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      f'dtype: {x.dtype}',
      # f'itemsize: {x.itemsize}',
      sep='\n')

<class 'numpy.ndarray'>:
[[[4.64161744e-310 0.00000000e+000 6.94683236e-310 6.94684841e-310]
  [6.94684844e-310 6.94683234e-310 6.94684836e-310 6.94684841e-310]
  [6.94683234e-310 6.94684842e-310 6.94684843e-310 6.94684843e-310]]

 [[6.94684843e-310 6.94684843e-310 6.94684842e-310 6.94683236e-310]
  [6.94683234e-310 6.94684840e-310 6.94684840e-310 6.94683237e-310]
  [6.94684827e-310 6.94684777e-310 6.94684777e-310 6.94684844e-310]]]
ndim: 3
shape: (2, 3, 4)
size: 24
dtype: float64
