# The basics

## Array creation

### Functions to create

- NumPy offers several functions to create arrays
  with the same shape and type as a given array:
  - `zeros_like` creates an array of zeros,
  - `ones_like` creates an array of ones,
  - `empty_lile` creates an array of uninitialized (arbitrary) data.
- By default,
  the type of the created array is the type of the given array
  but can also be specified.

In [1]:
import numpy as np

In [2]:
# Creates an arrays of zeros
# using 1d array of integers as prototype.

x_shape, x_start, x_step = (12, ), 1, 1
x_stop = x_start + x_step * (np.product(x_shape) - 1)
x = np.arange(
    start=x_start,
    stop=x_stop + x_step,
    step=x_step
).reshape(x_shape)

y = np.zeros_like(x)
z = np.zeros_like(x, dtype=float)

for _ in (x, y, z):
    print(f'{type(_)}:', _,
          f'shape: {_.shape}',
          f'dtype: {_.dtype}',
          sep='\n', end='\n\n')

<class 'numpy.ndarray'>:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64

<class 'numpy.ndarray'>:
[0 0 0 0 0 0 0 0 0 0 0 0]
shape: (12,)
dtype: int64

<class 'numpy.ndarray'>:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
shape: (12,)
dtype: float64



In [3]:
# Creates an arrays of ones
# using 2d array of floats as prototype.

x_shape, x_start, x_step = (3, 4), 1., 1.
x_stop = x_start + x_step * (np.product(x_shape) - 1)
x = np.arange(
    start=x_start,
    stop=x_stop + x_step,
    step=x_step
).reshape(x_shape)

y = np.ones_like(x)
z = np.ones_like(x, dtype=int)

for _ in (x, y, z):
    print(f'{type(_)}:', _,
          f'shape: {_.shape}',
          f'dtype: {_.dtype}',
          sep='\n', end='\n\n')

<class 'numpy.ndarray'>:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
shape: (3, 4)
dtype: float64

<class 'numpy.ndarray'>:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (3, 4)
dtype: float64

<class 'numpy.ndarray'>:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
shape: (3, 4)
dtype: int64



In [4]:
# Creates an arrays of randoms
# using 3d array of integers as prototype.

x_shape, x_start, x_step = (2, 2, 3), 1, 1
x_stop = x_start + x_step * (np.product(x_shape) - 1)
x = np.arange(
    start=x_start,
    stop=x_stop + x_step,
    step=x_step
).reshape(x_shape)

y = np.empty_like(x)
z = np.empty_like(x, dtype=float)

for _ in (x, y, z):
    print(f'{type(_)}:', _,
          f'shape: {_.shape}',
          f'dtype: {_.dtype}',
          sep='\n', end='\n\n')

<class 'numpy.ndarray'>:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape: (2, 2, 3)
dtype: int64

<class 'numpy.ndarray'>:
[[[4607182418800017408 4611686018427387904 4613937818241073152]
  [4616189618054758400 4617315517961601024 4618441417868443648]]

 [[4619567317775286272 4620693217682128896 4621256167635550208]
  [4621819117588971520 4622382067542392832 4622945017495814144]]]
shape: (2, 2, 3)
dtype: int64

<class 'numpy.ndarray'>:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
shape: (2, 2, 3)
dtype: float64

