# Printing Arrays

## Layout

When you print an array,
NumPy displays it in a similar way to nested lists,
but with the following layout:
* the last axis is printed from left to right,
* the second-to-last is printed from top to bottom,
* the rest are also printed from top to bottom,
  with each slice separated from the next by an empty line.

## Links

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Printing Arrays](https://numpy.org/doc/1.17/user/quickstart.html#printing-arrays)


In [1]:
import numpy as np


In [2]:
# Creates 1D array.
n = 12
x_min, x_step = 1, 1
x = np.arange(start=x_min, stop=x_min + n, step=x_step)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')


<class 'numpy.ndarray'>:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12


In [3]:
# Creates 2D ndarray by reshaping 1D ndarray.
n, m = 3, 4
x_min, x_step = 1, 1
x = np.arange(start=x_min,
              stop=x_min + n * m,
              step=x_step).reshape(n, m)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')


<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12


In [4]:
# Creates 3D ndarray by reshaping 1D ndarray.
k, m, n = 2, 3, 4
x_min, x_step = 1, 1
x = np.arange(start=x_min,
              stop=x_min + k * n * m,
              step=x_step).reshape(k, n, m)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}', '',
      sep='\n')


<class 'numpy.ndarray'>:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
ndim: 3
shape: (2, 4, 3)
size: 24

