# Printing Arrays

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Printing Arrays](https://numpy.org/doc/1.17/user/quickstart.html#printing-arrays)

If an array is too large to be printed,
NumPy automatically skips
the central part of the array
and only prints the corners.  
To disable this behaviour
and force NumPy to print the entire array,
you can change the printing options
using **set_printoptions**.

In [1]:
import numpy as np

In [2]:
# create 1d array

n = 1001
x_min = 1
x_step = 1
x = np.arange(
    start=x_min,
    stop=x_min + n,
    step=x_step)

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    sep='\n')

<class 'numpy.ndarray'>:
[   1    2    3 ...  999 1000 1001]
ndim: 1
shape: (1001,)
size: 1001


In [3]:
# create 2d array
# by reshaping 1d array

n, m = 100, 100
x_min = 1
x_step = 1
x = np.arange(
    start=x_min,
    stop=x_min + n * m,
    step=x_step).reshape(n, m)

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}', '',
    sep='\n')

<class 'numpy.ndarray'>:
[[    1     2     3 ...    98    99   100]
 [  101   102   103 ...   198   199   200]
 [  201   202   203 ...   298   299   300]
 ...
 [ 9701  9702  9703 ...  9798  9799  9800]
 [ 9801  9802  9803 ...  9898  9899  9900]
 [ 9901  9902  9903 ...  9998  9999 10000]]
ndim: 2
shape: (100, 100)
size: 10000

