# The basics

## Printing arrays

### Layout

When you print an array,
NumPy displays it in a similar way to nested lists,
but with the following layout:
- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom,
  with each slice separated from the next by an empty line.

In [1]:
import numpy as np

In [2]:
# Creates 1d array and prints it.

x_shape, x_min, x_step =(12, ), 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step
x = np.arange(
    start=x_min,
    stop=x_max + x_step,
    step=x_step
)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim: 1
shape: (12,)
size: 12


In [3]:
# Creates 2d array by reshaping 1d array
# and prints it.

x_shape, x_min, x_step =(3, 4), 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step
x = np.arange(
    start=x_min,
    stop=x_max + x_step,
    step=x_step
).reshape(x_shape)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12


In [4]:
# Creates 3d array by reshaping 1d array
# and prints it.

x_shape, x_min, x_step =(2, 3, 4), 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step
x = np.arange(
    start=x_min,
    stop=x_max + x_step,
    step=x_step
).reshape(x_shape)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
ndim: 3
shape: (2, 3, 4)
size: 24
