# The basics

## Printing arrays

### Skips

- If an array is too large to be printed,
  NumPy automatically skips the central part of the array and
  only prints the corners.  
- To disable this behaviour and
  force NumPy to print the entire array,
  you can change the printing options
  using `set_printoptions`.
  ```python
  np.set_printoptions(threshold=sys.maxsize)
  ```

In [1]:
import numpy as np

In [2]:
# Creates 1d array and prints it.

x_shape, x_min, x_step =(1001, ), 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step
x = np.arange(
    start=x_min,
    stop=x_max + x_step,
    step=x_step
)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[   1    2    3 ...  999 1000 1001]
ndim: 1
shape: (1001,)
size: 1001


In [3]:
# Creates 2d array by reshaping 1d array
# and prints it.

x_shape, x_min, x_step =(100, 100), 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step
x = np.arange(
    start=x_min,
    stop=x_max + x_step,
    step=x_step
).reshape(x_shape)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[[    1     2     3 ...    98    99   100]
 [  101   102   103 ...   198   199   200]
 [  201   202   203 ...   298   299   300]
 ...
 [ 9701  9702  9703 ...  9798  9799  9800]
 [ 9801  9802  9803 ...  9898  9899  9900]
 [ 9901  9902  9903 ...  9998  9999 10000]]
ndim: 2
shape: (100, 100)
size: 10000


In [4]:
# Creates 1d array and prints it
# while changing threshold from print options.

x_shape, x_min, x_step =(100, ), 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step
x = np.arange(
    start=x_min,
    stop=x_max + x_step,
    step=x_step
)

np.set_printoptions(threshold=x.size - 1)
print(x)

np.set_printoptions(threshold=x.size)
print(x)

[  1   2   3 ...  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
