# Basic Operations

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Basic Operations](https://numpy.org/doc/1.17/user/quickstart.html#basic-operations)

Unlike in many matrix languages,
the product operator *****
operates elementwise in NumPy arrays.
The matrix product can be performed
using the **@** operator
or the **dot** function or method.

In [44]:
import numpy as np

In [45]:
# elementwise and matrix product

x = np.array([
    [1, 2],
    [3 ,4]])

y = np.array([
    [1, 0],
    [0, 1]])

print(
    'x:', x, '',
    'y:', y, '',
    'x * y:', x * y, '',
    'x @ y:', x @ y, '',
    'np.dot(x, y):', np.dot(x, y), '',
    'x.dot(y):', x.dot(y),
    sep='\n')

x:
[[1 2]
 [3 4]]

y:
[[1 0]
 [0 1]]

x * y:
[[1 0]
 [0 4]]

x @ y:
[[1 2]
 [3 4]]

np.dot(x, y):
[[1 2]
 [3 4]]

x.dot(y):
[[1 2]
 [3 4]]


In [46]:
# elementwise and matrix product

x = np.array([
    [1, 2, 3],
    [4, 5, 6]])

y = np.array([
    [1, 0, 0],
    [0, 1, 0]])

z = np.array([
    [1, 0],
    [0, 1]])

print(
    'x:', x, '',
    'y:', y, '',
    'z:', z, '',
    'x * y:', x * y, '',
    'z @ x:', z @ x, '',
    'np.dot(z, x):', np.dot(z, x), '',
    'z.dot(x):', z.dot(x),
    sep='\n')

x:
[[1 2 3]
 [4 5 6]]

y:
[[1 0 0]
 [0 1 0]]

z:
[[1 0]
 [0 1]]

x * y:
[[1 0 0]
 [0 5 0]]

z @ x:
[[1 2 3]
 [4 5 6]]

np.dot(z, x):
[[1 2 3]
 [4 5 6]]

z.dot(x):
[[1 2 3]
 [4 5 6]]
