# Basic Operations

## Inplace operations

* Some operations, such as **+=** and ***=**,
  act in place to modify an existing array
  rather than create a new one.
* Type is not automatically converted.

## Links

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Basic Operations](https://numpy.org/doc/1.17/user/quickstart.html#basic-operations)


In [2]:
import numpy as np


In [3]:
# Inplace operations.

x, y = np.zeros((2, 2, 3), dtype=int) 

print('x:', x,
      sep='\n', end='\n\n')

x += 1
print('x += 1:', x,
      sep='\n', end='\n\n')

x *= 2
print('x *= 2:', x,
      sep='\n', end='\n\n')

print('y:', y,
      sep='\n', end='\n\n')

y += x
print('y += x:', y,
      sep='\n', end='\n\n')

y *= x
print('y *= x:', y,
      sep='\n', end='\n\n')


x:
[[0 0 0]
 [0 0 0]]

x += 1:
[[1 1 1]
 [1 1 1]]

x *= 2:
[[2 2 2]
 [2 2 2]]

y:
[[0 0 0]
 [0 0 0]]

y += x:
[[2 2 2]
 [2 2 2]]

y *= x:
[[4 4 4]
 [4 4 4]]



In [4]:
# Type casting error.

n = 3
x = np.ones(n)
y = np.ones(n, dtype=int)
x += y
y += x


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'