# The basics

## Basic operations

### Matrix operations

- Unlike in many matrix languages,
  the product operator `*` operates elementwise in NumPy arrays.
- The matrix product can be performed
  using the `@` operator or the `dot` function or method.

In [1]:
import numpy as np

In [2]:
# Elementwise and matrix product
# in case of square matrices.

# Set a couple of square matrices.
x = np.array([[1, 2], [3 ,4]])
y = np.array([[1, 0], [0, 1]])  # identity matrix

# Apply elemetwise product operator.
u = x * y

# Apply matrix product operator.
v = x @ y

# Apply matrix product function and method
# that must give the same results
# as a use of matrix product operator.
w = [np.dot(x, y), x.dot(y)]

check = np.all([_ == v for _ in w])

print(f'x:\n{x}',
      f'y:\n{y}',
      f'x * y:\n{u}',
      f'x @ y:\n{v}\n{check}',  
      sep='\n\n')

x:
[[1 2]
 [3 4]]

y:
[[1 0]
 [0 1]]

x * y:
[[1 0]
 [0 4]]

x @ y:
[[1 2]
 [3 4]]
True


In [3]:
# Elementwise and matrix product
# in case of 2d arraays.

# Set a couple of 2d arrays and a square matrix.
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 0, 0], [0, 1, 0]])
z = np.array([[1, 0], [0, 1]])  # identity matrix

# Apply elemetwise product operator.
u = y * x

# Apply matrix product operator.
v = z @ x

# Apply matrix product function and method
# that must give the same results
# as a use of matrix product operator.
w = [np.dot(z, x), z.dot(x)]

check = np.all([_ == v for _ in w])

print(f'x:\n{x}',
      f'y:\n{y}',
      f'z:\n{z}',
      f'y * x:\n{u}',
      f'z @ x:\n{v}\n{check}',  
      sep='\n\n')

x:
[[1 2 3]
 [4 5 6]]

y:
[[1 0 0]
 [0 1 0]]

z:
[[1 0]
 [0 1]]

y * x:
[[1 0 0]
 [0 5 0]]

z @ x:
[[1 2 3]
 [4 5 6]]
True
