# The basics

## Basic operations

### Inplace operations

- Some operations, such as `+=` and `*=`,
  act in place to modify an existing array
  rather than create a new one.
- Type is not automatically converted

In [1]:
import numpy as np

In [2]:
# Create a couple of zero filled 2d arrays
# and apply inplace operations to them.

x, y = np.zeros((2, 2, 3), dtype=int) 

print(f'x:\n{x}', end='\n\n')

x += 1
print(f'x += 1:\n{x}', end='\n\n')

x *= 2
print(f'x *= 2:\n{x}', end='\n\n')

print(f'y:\n{y}', end='\n\n')

y += x + 1
print(f'y += x + 1:\n{y}', end='\n\n')

y *= x + y
print(f'y *= x + y:\n{y}', end='\n\n')

x:
[[0 0 0]
 [0 0 0]]

x += 1:
[[1 1 1]
 [1 1 1]]

x *= 2:
[[2 2 2]
 [2 2 2]]

y:
[[0 0 0]
 [0 0 0]]

y += x + 1:
[[3 3 3]
 [3 3 3]]

y *= x + y:
[[15 15 15]
 [15 15 15]]



In [3]:
# Raise the type casting error.

# Create a couple of arrays
# of the same shape but the different types.
x = np.empty(3)  # float
y = np.empty_like(x, dtype=int)  # int

# Casting from int to float performs correctly.
x += y
# Casting from float to int leads to an error.
y += x

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'