# Indexing, Slicing and Iterating

## Multidimensional arrays

* Multidimensional arrays can have one index per axis.
  These indices are given in a tuple separated by commas.
* When fewer indices are provided than the number of axes,
  the missing indices are considered complete slices.
  In this case, the expression within brackets is treated 
  as an index followed by as many instances of colon **:**
  as needed to represent the remaining axes.
* NumPy also allows you to write this using dots **...**.
  The dots **...** represent as many colons **:** as needed
  to produce a complete indexing tuple.

## Links

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Indexing, Slicing and Iterating](https://numpy.org/doc/1.17/user/quickstart.html#indexing-slicing-and-iterating)


In [2]:
import numpy as np


In [3]:
# 2D array generation functions.

def f_1(i, j):
    """Return an integer item of 2D array depending on its indices."""
    n = 10
    return i * n + j


def f_2(m, n):
    """Return 2D array of an integers items depending on its shape."""
    return np.fromfunction(function=f_1, shape=(m, n), dtype=int)



In [7]:
# 2D random indexing.

x = f_2(3, 4)    

i = [np.random.randint(low=0, high=x.shape[k])
     for k in range(x.ndim)]
i = tuple(i)

print('2D array:',
      f'x =', x, '',
      
      'a couple of random indexes:',
      f'i = {i}', '',
      
      'value by a couple of indexes:',
      f'x[{i[0]},{i[1]}] = {x[i[0],i[1]]}',
      f'x[({i[0]},{i[1]})] = {x[i]}', '',
      
      'row by an index:',
      f'x[{i[0]},:] = {x[i[0],:]}',
      f'x[{i[0]},0:{x.shape[1]}] = {x[i[0],0:x.shape[1]]}',
      f'x[{i[0]},...] = {x[i[0],...]}',
      f'x[{i[0]}] = {x[i[0]]}','',
      
      'column by an index:',
      f'x[:,{i[1]}] = {x[:,i[1]]}',
      f'x[0:{x.shape[0]},{i[1]}] = {x[0:x.shape[0],i[1]]}',
      f'x[...,{i[1]}] = {x[...,i[1]]}',
      
      sep='\n')


2D array:
x =
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]

a couple of random indexes:
i = (2, 1)

value by a couple of indexes:
x[2,1] = 21
x[(2,1)] = 21

row by an index:
x[2,:] = [20 21 22 23]
x[2,0:4] = [20 21 22 23]
x[2,...] = [20 21 22 23]
x[2] = [20 21 22 23]

column by an index:
x[:,1] = [ 1 11 21]
x[0:3,1] = [ 1 11 21]
x[...,1] = [ 1 11 21]


In [8]:
# 2D random slice.

x = f_2(10, 10)

i = [[np.random.randint(low=0, high=x.shape[k] // 2)
      for k in range(x.ndim)],
     [np.random.randint(low=x.shape[k] // 2 + 1, high=x.shape[k])
      for k in range(x.ndim)]]
i = np.array(i)
i = i.transpose()

print('2D array:',
      f'x =', x, '',
      
      'a pair of couples of random indexes:',
      f'i =', i, '',
      
      '2D slice:',
      f'x[{i[0, 0]}:{i[0, 1]},{i[1, 0]}:{i[1, 1]}] =',
      x[i[0, 0]:i[0, 1], i[1, 0]:i[1, 1]],
      
      sep='\n')


2D array:
x =
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

a pair of couples of random indexes:
i =
[[2 9]
 [3 6]]

2D slice:
x[2:9,3:6] =
[[23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]
 [73 74 75]
 [83 84 85]]
