# Indexing, Slicing and Iterating

## Iterating

* Iterating over multidimensional arrays is done with respect to the first axis.
* However, if one wants to perform an operation on each element in the array,
  one can use the **ndarray.flat** attribute
  which is an iterator over all the elements of the array.

## Links

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[The Basics](https://numpy.org/doc/1.17/user/quickstart.html#the-basics) >>  
[Indexing, Slicing and Iterating](https://numpy.org/doc/1.17/user/quickstart.html#indexing-slicing-and-iterating)


In [1]:
import numpy as np


In [2]:
# Create 2D array
# using numpy.array fucntion
# and ndarray.reshape method.

n, m = 3, 4
x = np.arange(1, n * m + 1, 1).reshape(n, m)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12


In [3]:
# Iterate over the array
# with respect to the first axis.

i = 0
for y in x:
    print(i, y)
    i += 1


0 [1 2 3 4]
1 [5 6 7 8]
2 [ 9 10 11 12]


In [4]:
# Iterate over the array
# with respect to the first axis index.

for i in range(x.shape[0]):
    print(f'{i} {x[i]}')


0 [1 2 3 4]
1 [5 6 7 8]
2 [ 9 10 11 12]


In [5]:
# Iterate over all the elements of the array
# using ndarray.flat attribute.

i = 0
for y in x.flat:
    print(f'{i:>2}{y:>3}')
    i += 1


 0  1
 1  2
 2  3
 3  4
 4  5
 5  6
 6  7
 7  8
 8  9
 9 10
10 11
11 12


In [6]:
# Iterate over indeces of the array elements
# using ndarray.flat attribute.

for i in range(x.size):
    print(f'{i:>2}{x.flat[i]:>3}')


 0  1
 1  2
 2  3
 3  4
 4  5
 5  6
 6  7
 7  8
 8  9
 9 10
10 11
11 12
