# The basics

## Indexing, slicing and iterating

### Multidimensional arrays

- Multidimensional arrays can have one index per axis.
  These indices are given in a tuple separated by commas.
- When fewer indices are provided than the number of axes,
  the missing indices are considered complete slices.
  In this case, the expression within brackets is treated as
  an index followed by as many instances of colon `:` as needed
  to represent the remaining axes.
- NumPy also allows you to write this using dots `...`.
  The dots `...` represent as many colons `:` as needed
  to produce a complete indexing tuple.

In [1]:
import numpy as np

In [2]:
# Create 2d array generation functions.

def my_func_1(i, j):
    """Return an integer item of 2d array depending on its indices."""
    b  = 10, 1 # row and column bases
    return b[0] * i + b[1] * j

def my_func_2(m, n):
    """Return 2d array of an integers items depending on its shape."""
    return np.fromfunction(function=my_func_1, shape=(m, n), dtype=int)

In [3]:
# Apply indexing to ad array.

# Create 2d integer array of specified shape. 
x = my_func_2(3, 4)    

# Generate a couple of random row and column indexes.
i, j = [np.random.randint(low=0, high=x.shape[k])
        for k in range(x.ndim)]

print('2d array:',
      f'x =\n{x}\n',
      
      'a couple of random indexes:',
      f'i, j = {i}, {j}\n',
      
      'a value by a couple of indexes:',
      f'x[{i},{j}] = {x[i,j]}',
      f'x[({i},{j})] = {x[(i,j)]}\n',
      
      'a row by an index:',
      f'x[{i}] = {x[i]}',
      f'x[{i},:] = {x[i,:]}',
      f'x[{i},0:{x.shape[1]}] = {x[i,0:x.shape[1]]}',
      f'x[{i},...] = {x[i,...]}\n',
      
      'a column by an index:',
      f'x[:,{j}] = {x[:,j]}',
      f'x[0:{x.shape[0]},{j}] = {x[0:x.shape[0],j]}',
      f'x[...,{j}] = {x[...,j]}\n',
      
      sep='\n')

2d array:
x =
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]

a couple of random indexes:
i, j = 2, 1

a value by a couple of indexes:
x[2,1] = 21
x[(2,1)] = 21

a row by an index:
x[2] = [20 21 22 23]
x[2,:] = [20 21 22 23]
x[2,0:4] = [20 21 22 23]
x[2,...] = [20 21 22 23]

a column by an index:
x[:,1] = [ 1 11 21]
x[0:3,1] = [ 1 11 21]
x[...,1] = [ 1 11 21]



In [4]:
# Make a slice of 2d array.

# Create 2d integer array of specified shape.
x = my_func_2(10, 10)

# Create a pair of couples of
# random indexes from specified ranges.
i = [
    [np.random.randint(low=0, high=x.shape[k] // 2)
     for k in range(x.ndim)],
    [np.random.randint(low=x.shape[k] // 2 + 1, high=x.shape[k])
     for k in range(x.ndim)]
]
i = np.array(i).transpose()


print('2d array:',
      f'x =\n{x}\n',
      
      'a pair of couples of random indexes:',
      f'i =\n{i}\n',
      
      '2d slice:',
      f'x[{i[0, 0]}:{i[0, 1]},{i[1, 0]}:{i[1, 1]}] =',
      x[i[0, 0]:i[0, 1], i[1, 0]:i[1, 1]],
      
      sep='\n')

2d array:
x =
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

a pair of couples of random indexes:
i =
[[2 9]
 [4 6]]

2d slice:
x[2:9,4:6] =
[[24 25]
 [34 35]
 [44 45]
 [54 55]
 [64 65]
 [74 75]
 [84 85]]
