# The basics

## Indexing, slicing and iterating

### Iterating

- Iterating over multidimensional arrays is done with respect to the first axis.
- However, if you want to perform an operation on each element in the array,
  you can use the `ndarray.flat` attribute
  which is an iterator over all the elements of the array.

In [1]:
import numpy as np

In [2]:
# Create 1d array of integers and
# reshape it to make 2d one.

x_shape = 3, 4
x_min, x_step = 1, 1
x_max = x_min + (np.product(x_shape) - 1) * x_step 
x = np.arange(start=x_min,
              stop=x_max + x_step,
              step=x_step)
x = x.reshape(x_shape)

print(f'{type(x)}:', x,
      f'ndim: {x.ndim}',
      f'shape: {x.shape}',
      f'size: {x.size}',
      sep='\n')

<class 'numpy.ndarray'>:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndim: 2
shape: (3, 4)
size: 12


In [3]:
# Iterate over the array
# with respect to the first axis.

for _ in x:
    print(_)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [4]:
# Iterate over the array
# with respect to the first axis index.

for i in range(x.shape[0]):
    print(f'{i} {x[i]}')

0 [1 2 3 4]
1 [5 6 7 8]
2 [ 9 10 11 12]


In [5]:
# Iterate over all array elements.

for _ in x.flat:
    print(_)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
# Iterate over indices of all array elements.

for i in range(x.size):
    print(f'{i:>2} {x.flat[i]:>2}')

 0  1
 1  2
 2  3
 3  4
 4  5
 5  6
 6  7
 7  8
 8  9
 9 10
10 11
11 12
