# Changing the shape of an array

[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Changing the shape of an array](https://numpy.org/doc/1.17/user/quickstart.html#changing-the-shape-of-an-array)

1. An array has a shape given by the number of elements along each axis,
   which can be obtained using **ndarray.shape** attribute.
2. The following three commands all return a modified array,
   but do not change the original array:
    * **ndarray.ravel** method returns the array, flattened,
    * **ndarray.transpose** method returns the array, transposed,
    * **ndarray.reshape** method returns the array with a modified shape.
3. The **numpy.reshape** function returns its argument with a modified shape,
   whereas the **ndarray.resize** method modifies the array itself.
4. If a dimension is given as **-1** in a reshaping operation,
   the other dimensions are automatically calculated.


In [1]:
import numpy as np


In [2]:
# Create random array of random shape.

# Get the shape of 2D array,
# random but even,
# and within 10 in each direction.
s_limit = [1, 5]
while True:
    s = np.random.randint(low=s_limit[0], high=s_limit[1] + 1,
                          size=2)
    if s[0] == s[1]:
        continue
    s *= 2
    break

# Get random array.
x = np.random.rand(*s)
x = np.floor(10 * x)
x = np.array(x, dtype=int)

print(
    f'{type(x)}:', x,
    f'ndim: {x.ndim}',
    f'shape: {x.shape}',
    f'size: {x.size}',
    sep='\n')


<class 'numpy.ndarray'>:
[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]
ndim: 2
shape: (4, 10)
size: 40


In [3]:
# Get flattened array,

print('x', x,
      sep='\n', end='\n\n')

# using ndarray.flat attribute
# mutually with numpy.array function.
y = np.array(x.flat)
print('np.array(x.flat)', y,
      sep='\n', end='\n\n')

# using ndarray.ravel method.
y = x.ravel()
print('x.ravel()', y,
      sep='\n', end='\n\n')

# using ndarray.reshape method.
y = x.reshape(1, -1)[0]
print('x.reshape(1, -1)[0]', y,
      sep='\n', end='\n\n')

# using numpy.reshape function.
y = np.reshape(x, (1, -1))[0]
print('np.reshape(x, (1, -1))[0]', y,
      sep='\n', end='\n\n')


x
[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]

np.array(x.flat)
[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0
 4 0 4]

x.ravel()
[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0
 4 0 4]

x.reshape(1, -1)[0]
[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0
 4 0 4]

np.reshape(x, (1, -1))[0]
[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0
 4 0 4]



In [4]:
# Iterate over flattened array,
# using ndarray.flat attribute.

i = 0
print('{:>2}{:>2}'.format('i', 'x'))
for y in x.flat:
    print(f'{i:>2}{y:>2}')
    i += 1


 i x
 0 0
 1 5
 2 3
 3 0
 4 5
 5 6
 6 2
 7 1
 8 4
 9 4
10 2
11 5
12 5
13 8
14 1
15 7
16 1
17 5
18 7
19 5
20 8
21 5
22 2
23 8
24 1
25 6
26 6
27 2
28 2
29 7
30 9
31 7
32 6
33 9
34 7
35 3
36 0
37 4
38 0
39 4


In [5]:
# Get transposed array,

print('x', x,
      sep='\n', end='\n\n')

# using ndarray.T attribute.
y = x.T
print('x.T', y,
      sep='\n', end='\n\n')

# using ndarray.transpose method.
y = x.transpose()
print('x.transpose()', y,
      sep='\n', end='\n\n')

# using ndarray.reshape method
# mutually with ndarray.shape attribute. 
y = x.reshape(x.shape[::-1])
print('x.reshape(x.shape[::-1])', y,
      sep='\n', end='\n\n')

# using numpy.reshape function
# mutually with ndarray.shape attribute.
y = np.reshape(x, x.shape[::-1])
print('np.reshape(x, x.shape[::-1])', y,
      sep='\n', end='\n\n')


x
[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]

x.T
[[0 2 8 9]
 [5 5 5 7]
 [3 5 2 6]
 [0 8 8 9]
 [5 1 1 7]
 [6 7 6 3]
 [2 1 6 0]
 [1 5 2 4]
 [4 7 2 0]
 [4 5 7 4]]

x.transpose()
[[0 2 8 9]
 [5 5 5 7]
 [3 5 2 6]
 [0 8 8 9]
 [5 1 1 7]
 [6 7 6 3]
 [2 1 6 0]
 [1 5 2 4]
 [4 7 2 0]
 [4 5 7 4]]

x.reshape(x.shape[::-1])
[[0 5 3 0]
 [5 6 2 1]
 [4 4 2 5]
 [5 8 1 7]
 [1 5 7 5]
 [8 5 2 8]
 [1 6 6 2]
 [2 7 9 7]
 [6 9 7 3]
 [0 4 0 4]]

np.reshape(x, x.shape[::-1])
[[0 5 3 0]
 [5 6 2 1]
 [4 4 2 5]
 [5 8 1 7]
 [1 5 7 5]
 [8 5 2 8]
 [1 6 6 2]
 [2 7 9 7]
 [6 9 7 3]
 [0 4 0 4]]



In [6]:
# Reshape the array,
# using ndarray.reshape method,
# that doesn't modify an argument.

# Get the list of shapes.
s_0 = x.shape
s_1 = [s_0, # original shape
       # Halve the number of rows,
       # respectively increasing the number of columns.
       (int(s_0[0] / 2), s_0[1] * 2),
       # Halve the number of columns,
       # respectively increasing the number of rows.
       (s_0[0] * 2, int(s_0[1] /  2)),
       (1, -1), # one row shape
       (-1, 1)] # one column shape

# Iterate over the shape list.
for s in s_1:
    y = x.reshape(s)
    print(y, y.shape,
          sep='\n', end='\n\n')


[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]
(4, 10)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0 4 0 4]]
(2, 20)

[[0 5 3 0 5]
 [6 2 1 4 4]
 [2 5 5 8 1]
 [7 1 5 7 5]
 [8 5 2 8 1]
 [6 6 2 2 7]
 [9 7 6 9 7]
 [3 0 4 0 4]]
(8, 5)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3
  0 4 0 4]]
(1, 40)

[[0]
 [5]
 [3]
 [0]
 [5]
 [6]
 [2]
 [1]
 [4]
 [4]
 [2]
 [5]
 [5]
 [8]
 [1]
 [7]
 [1]
 [5]
 [7]
 [5]
 [8]
 [5]
 [2]
 [8]
 [1]
 [6]
 [6]
 [2]
 [2]
 [7]
 [9]
 [7]
 [6]
 [9]
 [7]
 [3]
 [0]
 [4]
 [0]
 [4]]
(40, 1)



In [7]:
# Reshape the array
# using numpy.reshape function,
# that doesn't modify an argument.

for s in s_1:
    y = np.reshape(x, s)
    print(y, y.shape,
          sep='\n', end='\n\n')


[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]
(4, 10)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0 4 0 4]]
(2, 20)

[[0 5 3 0 5]
 [6 2 1 4 4]
 [2 5 5 8 1]
 [7 1 5 7 5]
 [8 5 2 8 1]
 [6 6 2 2 7]
 [9 7 6 9 7]
 [3 0 4 0 4]]
(8, 5)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3
  0 4 0 4]]
(1, 40)

[[0]
 [5]
 [3]
 [0]
 [5]
 [6]
 [2]
 [1]
 [4]
 [4]
 [2]
 [5]
 [5]
 [8]
 [1]
 [7]
 [1]
 [5]
 [7]
 [5]
 [8]
 [5]
 [2]
 [8]
 [1]
 [6]
 [6]
 [2]
 [2]
 [7]
 [9]
 [7]
 [6]
 [9]
 [7]
 [3]
 [0]
 [4]
 [0]
 [4]]
(40, 1)



In [8]:
# Modify the array,
# using ndarray.shape attribute.

y = x.copy()
for s in s_1:
    y.shape = s
    print(y, y.shape,
          sep='\n', end='\n\n')


[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]
(4, 10)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0 4 0 4]]
(2, 20)

[[0 5 3 0 5]
 [6 2 1 4 4]
 [2 5 5 8 1]
 [7 1 5 7 5]
 [8 5 2 8 1]
 [6 6 2 2 7]
 [9 7 6 9 7]
 [3 0 4 0 4]]
(8, 5)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5 8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3
  0 4 0 4]]
(1, 40)

[[0]
 [5]
 [3]
 [0]
 [5]
 [6]
 [2]
 [1]
 [4]
 [4]
 [2]
 [5]
 [5]
 [8]
 [1]
 [7]
 [1]
 [5]
 [7]
 [5]
 [8]
 [5]
 [2]
 [8]
 [1]
 [6]
 [6]
 [2]
 [2]
 [7]
 [9]
 [7]
 [6]
 [9]
 [7]
 [3]
 [0]
 [4]
 [0]
 [4]]
(40, 1)



In [9]:
# Modify the array,
# using ndarray.resize method,
# wherein dimension equal to -1
# is not acceptable.

y = x.copy()
for s in s_1[:-2]:
    y.resize(s)
    print(y, y.shape,
          sep='\n', end='\n\n')


[[0 5 3 0 5 6 2 1 4 4]
 [2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7]
 [9 7 6 9 7 3 0 4 0 4]]
(4, 10)

[[0 5 3 0 5 6 2 1 4 4 2 5 5 8 1 7 1 5 7 5]
 [8 5 2 8 1 6 6 2 2 7 9 7 6 9 7 3 0 4 0 4]]
(2, 20)

[[0 5 3 0 5]
 [6 2 1 4 4]
 [2 5 5 8 1]
 [7 1 5 7 5]
 [8 5 2 8 1]
 [6 6 2 2 7]
 [9 7 6 9 7]
 [3 0 4 0 4]]
(8, 5)

