# Stacking together different arrays

## Row and column stack
* The function **numpy.column_stack** stacks 1D arrays
  as columns into a 2D array.
  It is equivalent to **numpy.hstack** only for 2D arrays.
* On the other hand, the function **numpy.row_stack**
  is equivalent to **vstack** for any input arrays.

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Stacking together different arrays](https://numpy.org/doc/1.17/user/quickstart.html#stacking-together-different-arrays)

In [1]:
import numpy as np
from numpy import newaxis


### 1D array stacking

In [2]:
# Creates two 1D arrays of the same length,
# containig random integers in the range from 0 to 9.
n, s = 2, 3 
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [3]:
# Creates 2D array
# and stacks 1D arrays along its first axis,
# herewith row stack function is equivalent
# to verticle stack one.
z = [np.vstack((x, y)),
     np.row_stack((x, y))]
# Which works just like
# z = [np.vstack((x[newaxis,:], y[newaxis,:])),
#      np.row_stack((x[newaxis,:], y[newaxis,:]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]),
      sep='\n')


1:
[0 1 7]
(3,)

2:
[7 7 7]
(3,)

vstack:
[[0 1 7]
 [7 7 7]]
(2, 3)

row_stack:
[[0 1 7]
 [7 7 7]]
(2, 3)

check:
True


In [4]:
# Stacks 1D arrays along single axis,
# using horisontal stack function,
# and stack 1D arrays as columns into a 2D array,
# using column stack function.
z = [np.hstack((x, y)),
     # Which works just like 
     # np.ravel(np.hstack((x.reshape(1, -1), y.reshape(1, -1)))),
     # or
     # np.ravel(np.hstack((x[newaxis,:], y[newaxis,:]))),
     # or
     # np.ravel(np.column_stack((x.reshape(1, -1), y.reshape(1, -1)))),
     # or
     np.ravel(np.column_stack((x[newaxis,:], y[newaxis,:]))),
     
     np.column_stack((x, y)),
     # Which works just like
     # np.column_stack((x.reshape(-1, 1), y.reshape(-1, 1))),
     # or
     # np.column_stack((x[:,newaxis], y[:,newaxis])),
     # or
     # np.hstack((x.reshape(-1, 1), y.reshape(-1, 1))),
     # or
     np.hstack((x[:,newaxis], y[:,newaxis]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack reshaped:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]), '',
      'column_stack:', z[2], z[2].shape, '',      
      'hstack reshaped:', z[3], z[3].shape, '',
      'check:', np.all(z[2] == z[3]), '',
      sep='\n')


1:
[0 1 7]
(3,)

2:
[7 7 7]
(3,)

hstack:
[0 1 7 7 7 7]
(6,)

column_stack reshaped:
[0 1 7 7 7 7]
(6,)

check:
True

column_stack:
[[0 7]
 [1 7]
 [7 7]]
(3, 2)

hstack reshaped:
[[0 7]
 [1 7]
 [7 7]]
(3, 2)

check:
True



### 2D array stacking

In [5]:
# Creates two 2D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [6]:
# Stacks 2D arrays along first axis,
# herewith row stack function
# is equivalent to vertical stack one.
z = [np.vstack((x, y)),
     np.row_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]), '',
      sep='\n')


1:
[[2 9 6 0]
 [4 2 3 8]
 [8 8 3 2]]
(3, 4)

2:
[[1 0 4 7]
 [4 4 0 9]
 [8 0 4 5]]
(3, 4)

vstack:
[[2 9 6 0]
 [4 2 3 8]
 [8 8 3 2]
 [1 0 4 7]
 [4 4 0 9]
 [8 0 4 5]]
(6, 4)

row_stack:
[[2 9 6 0]
 [4 2 3 8]
 [8 8 3 2]
 [1 0 4 7]
 [4 4 0 9]
 [8 0 4 5]]
(6, 4)

check:
True



In [7]:
# Stacks 2D arrays along second axis,
# herewith column stack function
# is equivalent to horisontal stack one.
z = [np.hstack((x, y)),
     np.column_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]),
      sep='\n')


1:
[[2 9 6 0]
 [4 2 3 8]
 [8 8 3 2]]
(3, 4)

2:
[[1 0 4 7]
 [4 4 0 9]
 [8 0 4 5]]
(3, 4)

hstack:
[[2 9 6 0 1 0 4 7]
 [4 2 3 8 4 4 0 9]
 [8 8 3 2 8 0 4 5]]
(3, 8)

column_stack:
[[2 9 6 0 1 0 4 7]
 [4 2 3 8 4 4 0 9]
 [8 8 3 2 8 0 4 5]]
(3, 8)

check:
True


### 3D array stacking

In [8]:
# Creates two 3D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (2, 3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [9]:
# Stacks 3D arrays along first axis,
# herewith row stack function
# is equivalent to vertical stack one.
z = [np.vstack((x, y)),
     np.row_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]),
      sep='\n')


1:
[[[1 6 6 6]
  [6 4 4 2]
  [8 3 9 8]]

 [[2 1 7 1]
  [3 1 7 1]
  [7 1 0 4]]]
(2, 3, 4)

2:
[[[1 7 5 8]
  [4 3 3 7]
  [2 2 8 9]]

 [[6 2 0 6]
  [5 5 9 4]
  [9 2 9 3]]]
(2, 3, 4)

vstack:
[[[1 6 6 6]
  [6 4 4 2]
  [8 3 9 8]]

 [[2 1 7 1]
  [3 1 7 1]
  [7 1 0 4]]

 [[1 7 5 8]
  [4 3 3 7]
  [2 2 8 9]]

 [[6 2 0 6]
  [5 5 9 4]
  [9 2 9 3]]]
(4, 3, 4)

row_stack:
[[[1 6 6 6]
  [6 4 4 2]
  [8 3 9 8]]

 [[2 1 7 1]
  [3 1 7 1]
  [7 1 0 4]]

 [[1 7 5 8]
  [4 3 3 7]
  [2 2 8 9]]

 [[6 2 0 6]
  [5 5 9 4]
  [9 2 9 3]]]
(4, 3, 4)

check:
True


In [10]:
# Stacks 3D arrays along second axis,
# herewith column stack function
# is equivalent to horisontal stack one.
z = [np.hstack((x, y)),
     np.column_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]),
      sep='\n')


1:
[[[1 6 6 6]
  [6 4 4 2]
  [8 3 9 8]]

 [[2 1 7 1]
  [3 1 7 1]
  [7 1 0 4]]]
(2, 3, 4)

2:
[[[1 7 5 8]
  [4 3 3 7]
  [2 2 8 9]]

 [[6 2 0 6]
  [5 5 9 4]
  [9 2 9 3]]]
(2, 3, 4)

hstack:
[[[1 6 6 6]
  [6 4 4 2]
  [8 3 9 8]
  [1 7 5 8]
  [4 3 3 7]
  [2 2 8 9]]

 [[2 1 7 1]
  [3 1 7 1]
  [7 1 0 4]
  [6 2 0 6]
  [5 5 9 4]
  [9 2 9 3]]]
(2, 6, 4)

column_stack:
[[[1 6 6 6]
  [6 4 4 2]
  [8 3 9 8]
  [1 7 5 8]
  [4 3 3 7]
  [2 2 8 9]]

 [[2 1 7 1]
  [3 1 7 1]
  [7 1 0 4]
  [6 2 0 6]
  [5 5 9 4]
  [9 2 9 3]]]
(2, 6, 4)

check:
True
