# Stacking together different arrays

## Row and column stack
* The function **numpy.column_stack** stacks 1D arrays
  as columns into a 2D array.
  It is equivalent to **numpy.hstack** only for 2D arrays.
* On the other hand, the function **numpy.row_stack**
  is equivalent to **vstack** for any input arrays.

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Stacking together different arrays](https://numpy.org/doc/1.17/user/quickstart.html#stacking-together-different-arrays)

In [1]:
import numpy as np
from numpy import newaxis


### 1D array stacking

In [2]:
# Creates two 1D arrays of the same length,
# containig random integers in the range from 0 to 9.
n, s = 2, 3 
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [3]:
# Creates 2D array
# and stacks 1D arrays along its first axis,
# herewith row stack function is equivalent
# to verticle stack one.
z = [np.vstack((x, y)),
     np.row_stack((x, y))]
# Which works just like
# z = [np.vstack((x[newaxis,:], y[newaxis,:])),
#      np.row_stack((x[newaxis,:], y[newaxis,:]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', z[0] == z[1],
      sep='\n')


1:
[8 8 9]
(3,)

2:
[4 7 6]
(3,)

vstack:
[[8 8 9]
 [4 7 6]]
(2, 3)

row_stack:
[[8 8 9]
 [4 7 6]]
(2, 3)

check:
[[ True  True  True]
 [ True  True  True]]


In [4]:
# Stacks 1D arrays along single axis,
# using horisontal stack function,
# and stack 1D arrays as columns into a 2D array,
# using column stack function.
z = [np.hstack((x, y)),
     # Which works just like 
     # np.ravel(np.hstack((x.reshape(1, -1), y.reshape(1, -1)))),
     # or
     # np.ravel(np.hstack((x[newaxis,:], y[newaxis,:]))),
     # or
     # np.ravel(np.column_stack((x.reshape(1, -1), y.reshape(1, -1)))),
     # or
     np.ravel(np.column_stack((x[newaxis,:], y[newaxis,:]))),
     
     np.column_stack((x, y)),
     # Which works just like
     # np.column_stack((x.reshape(-1, 1), y.reshape(-1, 1))),
     # or
     # np.column_stack((x[:,newaxis], y[:,newaxis])),
     # or
     # np.hstack((x.reshape(-1, 1), y.reshape(-1, 1))),
     # or
     np.hstack((x[:,newaxis], y[:,newaxis]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack reshaped:', z[1], z[1].shape, '',
      'check:', z[0] == z[1], '',
      'column_stack:', z[2], z[2].shape, '',      
      'hstack reshaped:', z[3], z[3].shape, '',
      'check:', z[2] == z[3], '',
      sep='\n')


1:
[8 8 9]
(3,)

2:
[4 7 6]
(3,)

hstack:
[8 8 9 4 7 6]
(6,)

column_stack reshaped:
[8 8 9 4 7 6]
(6,)

check:
[ True  True  True  True  True  True]

column_stack:
[[8 4]
 [8 7]
 [9 6]]
(3, 2)

hstack reshaped:
[[8 4]
 [8 7]
 [9 6]]
(3, 2)

check:
[[ True  True]
 [ True  True]
 [ True  True]]



### 2D array stacking

In [5]:
# Creates two 2D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [6]:
# Stacks 2D arrays along first axis,
# herewith row stack function
# is equivalent to vertical stack one.
z = [np.vstack((x, y)),
     np.row_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', z[0] == z[1], '',
      sep='\n')


1:
[[5 8 5 2]
 [0 8 9 2]
 [8 5 3 8]]
(3, 4)

2:
[[5 7 8 7]
 [0 3 4 8]
 [9 4 8 8]]
(3, 4)

vstack:
[[5 8 5 2]
 [0 8 9 2]
 [8 5 3 8]
 [5 7 8 7]
 [0 3 4 8]
 [9 4 8 8]]
(6, 4)

row_stack:
[[5 8 5 2]
 [0 8 9 2]
 [8 5 3 8]
 [5 7 8 7]
 [0 3 4 8]
 [9 4 8 8]]
(6, 4)

check:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]



In [7]:
# Stacks 2D arrays along second axis,
# herewith column stack function
# is equivalent to horisontal stack one.
z = [np.hstack((x, y)),
     np.column_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'check:', z[0] == z[1],
      sep='\n')


1:
[[5 8 5 2]
 [0 8 9 2]
 [8 5 3 8]]
(3, 4)

2:
[[5 7 8 7]
 [0 3 4 8]
 [9 4 8 8]]
(3, 4)

hstack:
[[5 8 5 2 5 7 8 7]
 [0 8 9 2 0 3 4 8]
 [8 5 3 8 9 4 8 8]]
(3, 8)

column_stack:
[[5 8 5 2 5 7 8 7]
 [0 8 9 2 0 3 4 8]
 [8 5 3 8 9 4 8 8]]
(3, 8)

check:
[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


### 3D array stacking

In [8]:
# Creates two 3D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (2, 3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [9]:
# Stacks 3D arrays along first axis,
# herewith row stack function
# is equivalent to vertical stack one.
z = [np.vstack((x, y)),
     np.row_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', z[0] == z[1],
      sep='\n')


1:
[[[3 6 9 7]
  [9 5 6 3]
  [3 4 0 2]]

 [[2 2 7 3]
  [7 6 1 3]
  [8 6 9 4]]]
(2, 3, 4)

2:
[[[3 3 1 5]
  [9 2 0 2]
  [8 1 9 1]]

 [[0 4 2 0]
  [5 7 1 8]
  [9 8 2 5]]]
(2, 3, 4)

vstack:
[[[3 6 9 7]
  [9 5 6 3]
  [3 4 0 2]]

 [[2 2 7 3]
  [7 6 1 3]
  [8 6 9 4]]

 [[3 3 1 5]
  [9 2 0 2]
  [8 1 9 1]]

 [[0 4 2 0]
  [5 7 1 8]
  [9 8 2 5]]]
(4, 3, 4)

row_stack:
[[[3 6 9 7]
  [9 5 6 3]
  [3 4 0 2]]

 [[2 2 7 3]
  [7 6 1 3]
  [8 6 9 4]]

 [[3 3 1 5]
  [9 2 0 2]
  [8 1 9 1]]

 [[0 4 2 0]
  [5 7 1 8]
  [9 8 2 5]]]
(4, 3, 4)

check:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [10]:
# Stacks 3D arrays along second axis,
# herewith column stack function
# is equivalent to horisontal stack one.
z = [np.hstack((x, y)),
     np.column_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'check:', z[0] == z[1],
      sep='\n')


1:
[[[3 6 9 7]
  [9 5 6 3]
  [3 4 0 2]]

 [[2 2 7 3]
  [7 6 1 3]
  [8 6 9 4]]]
(2, 3, 4)

2:
[[[3 3 1 5]
  [9 2 0 2]
  [8 1 9 1]]

 [[0 4 2 0]
  [5 7 1 8]
  [9 8 2 5]]]
(2, 3, 4)

hstack:
[[[3 6 9 7]
  [9 5 6 3]
  [3 4 0 2]
  [3 3 1 5]
  [9 2 0 2]
  [8 1 9 1]]

 [[2 2 7 3]
  [7 6 1 3]
  [8 6 9 4]
  [0 4 2 0]
  [5 7 1 8]
  [9 8 2 5]]]
(2, 6, 4)

column_stack:
[[[3 6 9 7]
  [9 5 6 3]
  [3 4 0 2]
  [3 3 1 5]
  [9 2 0 2]
  [8 1 9 1]]

 [[2 2 7 3]
  [7 6 1 3]
  [8 6 9 4]
  [0 4 2 0]
  [5 7 1 8]
  [9 8 2 5]]]
(2, 6, 4)

check:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
