# Stacking together different arrays

## Concatenate
* **numpy.concatenate** joins a sequence of arrays along an existing axis.
* The arrays must have the same shape,
  except in the dimension corresponding to axis (the first, by default).

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Stacking together different arrays](https://numpy.org/doc/1.17/user/quickstart.html#stacking-together-different-arrays)

In [1]:
import numpy as np
from numpy import newaxis


### 1D array concatenate

In [2]:
# Creates two 1D arrays of the same length,
# containig random integers in the range from 0 to 9.
n, s = 2, 3
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [3]:
# Creates 2D array
# and stacks 1D arrays along first axis,
# herewith row stack function is equivalent
# to verticle stack one.
z = [np.vstack((x, y)),
     # Which works just like 
     np.row_stack((x, y)),
     # or
     # np.concatenate((x.reshape(1, -1), y.reshape(1, -1))),
     np.concatenate((x[newaxis,:], y[newaxis,:]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', z[0] == z[1], '',
      'concatenate reshaped:', z[2], z[2].shape, '',
      'check:', z[0] == z[2],
      sep='\n')


1:
[9 6 9]
(3,)

2:
[1 6 9]
(3,)

vstack:
[[9 6 9]
 [1 6 9]]
(2, 3)

row_stack:
[[9 6 9]
 [1 6 9]]
(2, 3)

check:
[[ True  True  True]
 [ True  True  True]]

concatenate reshaped:
[[9 6 9]
 [1 6 9]]
(2, 3)

check:
[[ True  True  True]
 [ True  True  True]]


In [4]:
# Concatenates 1D arrays along single axis,
# which is equivalent to horisontal stack.
z = [np.hstack((x, y)),
     # Which works just like
     np.concatenate((x, y)),
     # or
     # np.ravel(np.column_stack((x.reshape((1, -1)), y.reshape((1, -1))))),
     # or
     np.ravel(np.column_stack((x[newaxis,:], y[newaxis,:])))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'concatenate:', z[1], z[1].shape, '',
      'check:', z[0] == z[1], '',
      'column_stack reshaped:', z[2], z[2].shape, '',
      'check:', z[0] == z[2], '',
      sep='\n')


1:
[9 6 9]
(3,)

2:
[1 6 9]
(3,)

hstack:
[9 6 9 1 6 9]
(6,)

concatenate:
[9 6 9 1 6 9]
(6,)

check:
[ True  True  True  True  True  True]

column_stack reshaped:
[9 6 9 1 6 9]
(6,)

check:
[ True  True  True  True  True  True]



### 2D array concatenate

In [5]:
# Creates two 2D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [6]:
# Concatenates 2D arrays along first axis,
# which is equivalent to vertical or row stack.
z = [np.vstack((x, y)),
     np.row_stack((x, y)),
     np.concatenate((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', z[0] == z[2], '',
      sep='\n')


1:
[[7 4 8 4]
 [1 0 1 4]
 [4 2 5 3]]
(3, 4)

2:
[[3 5 1 9]
 [5 1 7 5]
 [1 4 4 1]]
(3, 4)

vstack:
[[7 4 8 4]
 [1 0 1 4]
 [4 2 5 3]
 [3 5 1 9]
 [5 1 7 5]
 [1 4 4 1]]
(6, 4)

row_stack:
[[7 4 8 4]
 [1 0 1 4]
 [4 2 5 3]
 [3 5 1 9]
 [5 1 7 5]
 [1 4 4 1]]
(6, 4)

concatenate:
[[7 4 8 4]
 [1 0 1 4]
 [4 2 5 3]
 [3 5 1 9]
 [5 1 7 5]
 [1 4 4 1]]
(6, 4)

check:
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]



In [7]:
# Concatenates 2D arrays along second axis,
# which is equivalent to horisontal or column stack.
z = [np.hstack((x, y)),
     np.column_stack((x, y)),
     np.concatenate((x, y), axis=1)]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', z[0] == z[2],
      sep='\n')


1:
[[7 4 8 4]
 [1 0 1 4]
 [4 2 5 3]]
(3, 4)

2:
[[3 5 1 9]
 [5 1 7 5]
 [1 4 4 1]]
(3, 4)

hstack:
[[7 4 8 4 3 5 1 9]
 [1 0 1 4 5 1 7 5]
 [4 2 5 3 1 4 4 1]]
(3, 8)

column_stack:
[[7 4 8 4 3 5 1 9]
 [1 0 1 4 5 1 7 5]
 [4 2 5 3 1 4 4 1]]
(3, 8)

concatenate:
[[7 4 8 4 3 5 1 9]
 [1 0 1 4 5 1 7 5]
 [4 2 5 3 1 4 4 1]]
(3, 8)

check:
[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


### 3D array concatenate

In [8]:
# Creates two 3D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (2, 3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [9]:
# Concatenates 3D arrays along first axis,
# which is equivalent to vertical or row stack.
z = [np.vstack((x, y)),
     np.row_stack((x, y)),
     np.concatenate((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', z[0] == z[2],
      sep='\n')


1:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]]]
(2, 3, 4)

2:
[[[6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(2, 3, 4)

vstack:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]]

 [[6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(4, 3, 4)

row_stack:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]]

 [[6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(4, 3, 4)

concatenate:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]]

 [[6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(4, 3, 4)

check:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ Tr

In [10]:
# Concatenates 3D arrays along second axis,
# which is equivalent to horisontal or column stack.
z = [np.hstack((x, y)),
     np.column_stack((x, y)),
     np.concatenate((x, y), axis=1)]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', z[0] == z[2],
      sep='\n')


1:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]]]
(2, 3, 4)

2:
[[[6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(2, 3, 4)

hstack:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]
  [6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]
  [4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(2, 6, 4)

column_stack:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]
  [6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]
  [4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(2, 6, 4)

concatenate:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]
  [6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]
  [4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(2, 6, 4)

check:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  Tru

In [11]:
# Concatenates 3D arrays along third axis.
z = np.concatenate((x, y), axis=2)

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'concatenate:', z, z.shape, '',
      'check 1:', x == z[...,:x.shape[2]], '',
      'check 2:', y == z[...,y.shape[2]:],
      sep='\n')

1:
[[[5 0 7 5]
  [5 9 9 3]
  [3 3 0 2]]

 [[1 5 9 9]
  [6 3 7 2]
  [6 0 1 6]]]
(2, 3, 4)

2:
[[[6 3 7 1]
  [3 8 2 1]
  [6 8 5 0]]

 [[4 4 4 8]
  [2 4 5 0]
  [8 5 0 3]]]
(2, 3, 4)

concatenate:
[[[5 0 7 5 6 3 7 1]
  [5 9 9 3 3 8 2 1]
  [3 3 0 2 6 8 5 0]]

 [[1 5 9 9 4 4 4 8]
  [6 3 7 2 2 4 5 0]
  [6 0 1 6 8 5 0 3]]]
(2, 3, 8)

check 1:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]

check 2:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]
