# Stacking together different arrays

## Concatenate
* **numpy.concatenate** joins a sequence of arrays
  along an existing axis.
* The arrays must have the same shape,
  except in the dimension corresponding to axis.
* By default the axis along which the arrays will be joined is 0.
  If axis is None, arrays are flattened before use.
   
## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Stacking together different arrays](https://numpy.org/doc/1.17/user/quickstart.html#stacking-together-different-arrays)

In [1]:
import numpy as np


In [2]:
# Creates two 2D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [3]:
# Concatenates 2D arrays along different axes.
a = [0, 1, None]
z = [np.concatenate((x, y), axis=_) for _ in a]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'concatenate', '',
      sep='\n')
for i in range(len(a)):
    print(f'axis: {a[i]}',
          z[i],
          z[i].shape, '',
          sep='\n')


1:
[[2 2 4 3]
 [3 5 5 3]
 [4 8 0 8]]
(3, 4)

2:
[[9 9 8 2]
 [5 9 9 9]
 [9 9 1 4]]
(3, 4)

concatenate

axis: 0
[[2 2 4 3]
 [3 5 5 3]
 [4 8 0 8]
 [9 9 8 2]
 [5 9 9 9]
 [9 9 1 4]]
(6, 4)

axis: 1
[[2 2 4 3 9 9 8 2]
 [3 5 5 3 5 9 9 9]
 [4 8 0 8 9 9 1 4]]
(3, 8)

axis: None
[2 2 4 3 3 5 5 3 4 8 0 8 9 9 8 2 5 9 9 9 9 9 1 4]
(24,)

