# Stacking together different arrays

## Stacking along axis
* Several arrays can be stacked together along different axes,
  using **numpy.vstack** and **numpy.hstack** functions.
* In general, for arrays of with more than two dimensions,
  **hstack** stacks along their second axes,
  **vstack** stacks along their first axes.

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Stacking together different arrays](https://numpy.org/doc/1.17/user/quickstart.html#stacking-together-different-arrays)

In [1]:
import numpy as np
from numpy import newaxis


### 1D array stacking

In [2]:
# Creates two 1D arrays of the same length,
# containig random integers in the range from 0 to 9.
n, s = 2, 3
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [3]:
# Creates 2D array 
# and stacks 1D arrays along its first axis,
# using verticle stack function.
z = np.vstack((x, y))
# Which works just like
# z = np.vstack((x.reshape(1, -1), y.reshape(1, -1)))
# or
# z = np.vstack((x[newaxis,:], y[newaxis,:]))

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z, z.shape, '',
      'check 1:', np.all(x == z[0,:]), '',
      'check 2:', np.all(y == z[1,:]),
      sep='\n')


1:
[2 9 4]
(3,)

2:
[8 5 6]
(3,)

vstack:
[[2 9 4]
 [8 5 6]]
(2, 3)

check 1:
True

check 2:
True


In [4]:
# Stacks 1D arrays along single axis,
# using horisontal stack function.
z = np.hstack((x, y))
# Which works just like
#z = np.ravel(np.hstack((x.reshape(1, -1), y.reshape(1, -1))))
# or
#z = np.ravel(np.hstack((x[newaxis,:], y[newaxis,:])))

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z, z.shape, '',
      'check 1:', np.all(x == z[:x.size]), '',
      'check 2:', np.all(y == z[y.size:]),
      sep='\n')


1:
[2 9 4]
(3,)

2:
[8 5 6]
(3,)

hstack:
[2 9 4 8 5 6]
(6,)

check 1:
True

check 2:
True


### 2D array stacking

In [5]:
# Creates two 2D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [6]:
# Stacks 2D arrays along first axis,
# using vertical stack function.
z = np.vstack((x, y))

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z, z.shape, '',
      'check 1:', np.all(x == z[:x.shape[0],:]), '',
      'check 2:', np.all(y == z[y.shape[0]:,:]),
      sep='\n')


1:
[[0 1 7 1]
 [9 1 0 7]
 [8 1 5 3]]
(3, 4)

2:
[[1 8 6 2]
 [0 6 2 1]
 [9 0 4 4]]
(3, 4)

vstack:
[[0 1 7 1]
 [9 1 0 7]
 [8 1 5 3]
 [1 8 6 2]
 [0 6 2 1]
 [9 0 4 4]]
(6, 4)

check 1:
True

check 2:
True


In [7]:
# Stacks 2D arrays along second axis,
# using horisontal stack function.
z = np.hstack((x, y))

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z, z.shape, '',
      'check 1:', np.all(x == z[:,:x.shape[1]]), '',
      'check 2:', np.all(y == z[:,y.shape[1]:]),
      sep='\n')


1:
[[0 1 7 1]
 [9 1 0 7]
 [8 1 5 3]]
(3, 4)

2:
[[1 8 6 2]
 [0 6 2 1]
 [9 0 4 4]]
(3, 4)

hstack:
[[0 1 7 1 1 8 6 2]
 [9 1 0 7 0 6 2 1]
 [8 1 5 3 9 0 4 4]]
(3, 8)

check 1:
True

check 2:
True


### 3D array stacking

In [8]:
# Creates two 3D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (2, 3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]


In [9]:
# Stacks 3D arrays along first axis,
# using vertical stack function.
z = np.vstack((x, y))

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z, z.shape, '',
      'check 1', np.all(x == z[:x.shape[0],...]), '',
      'check 2', np.all(y == z[y.shape[0]:,...]),
      sep='\n')


1:
[[[8 2 7 4]
  [2 8 1 5]
  [8 0 0 5]]

 [[3 6 2 9]
  [5 3 9 4]
  [9 2 8 5]]]
(2, 3, 4)

2:
[[[5 4 8 4]
  [4 5 4 3]
  [2 7 1 1]]

 [[5 6 0 6]
  [2 8 2 8]
  [9 7 5 0]]]
(2, 3, 4)

vstack:
[[[8 2 7 4]
  [2 8 1 5]
  [8 0 0 5]]

 [[3 6 2 9]
  [5 3 9 4]
  [9 2 8 5]]

 [[5 4 8 4]
  [4 5 4 3]
  [2 7 1 1]]

 [[5 6 0 6]
  [2 8 2 8]
  [9 7 5 0]]]
(4, 3, 4)

check 1
True

check 2
True


In [10]:
# Stacks 3D arrays along second axis,
# using horisontal stack function.
z = np.hstack((x, y))

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z, z.shape, '',
      'check 1:', np.all(x == z[:,:x.shape[1],:]), '',
      'check 2:', np.all(y == z[:,y.shape[1]:,:]),
      sep='\n')


1:
[[[8 2 7 4]
  [2 8 1 5]
  [8 0 0 5]]

 [[3 6 2 9]
  [5 3 9 4]
  [9 2 8 5]]]
(2, 3, 4)

2:
[[[5 4 8 4]
  [4 5 4 3]
  [2 7 1 1]]

 [[5 6 0 6]
  [2 8 2 8]
  [9 7 5 0]]]
(2, 3, 4)

hstack:
[[[8 2 7 4]
  [2 8 1 5]
  [8 0 0 5]
  [5 4 8 4]
  [4 5 4 3]
  [2 7 1 1]]

 [[3 6 2 9]
  [5 3 9 4]
  [9 2 8 5]
  [5 6 0 6]
  [2 8 2 8]
  [9 7 5 0]]]
(2, 6, 4)

check 1:
True

check 2:
True
