# Stacking together different arrays

## Concatenate
* **numpy.concatenate** joins a sequence of arrays along an existing axis.
* The arrays must have the same shape,
  except in the dimension corresponding to axis (the first, by default).

In [1]:
import numpy as np
from numpy import newaxis

### 1D array concatenate

In [2]:
# Creates two 1D arrays of the same length,
# containig random integers in the range from 0 to 9.
n, s = 2, 3
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]

In [3]:
# Creates 2D array
# and stacks 1D arrays along first axis,
# herewith row stack function is equivalent
# to verticle stack one.
z = [np.vstack((x, y)),
     # Which works just like 
     np.row_stack((x, y)),
     # or
     # np.concatenate((x.reshape(1, -1), y.reshape(1, -1))),
     np.concatenate((x[newaxis,:], y[newaxis,:]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]), '',
      'concatenate reshaped:', z[2], z[2].shape, '',
      'check:', np.all(z[0] == z[2]),
      sep='\n')

1:
[9 5 0]
(3,)

2:
[0 4 6]
(3,)

vstack:
[[9 5 0]
 [0 4 6]]
(2, 3)

row_stack:
[[9 5 0]
 [0 4 6]]
(2, 3)

check:
True

concatenate reshaped:
[[9 5 0]
 [0 4 6]]
(2, 3)

check:
True


In [4]:
# Concatenates 1D arrays along single axis,
# which is equivalent to horisontal stack.
z = [np.hstack((x, y)),
     # Which works just like
     np.concatenate((x, y)),
     # or
     # np.ravel(np.column_stack((x.reshape((1, -1)), y.reshape((1, -1))))),
     # or
     np.ravel(np.column_stack((x[newaxis,:], y[newaxis,:])))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'concatenate:', z[1], z[1].shape, '',
      'check:', np.all(z[0] == z[1]), '',
      'column_stack reshaped:', z[2], z[2].shape, '',
      'check:', np.all(z[0] == z[2]), '',
      sep='\n')

1:
[9 5 0]
(3,)

2:
[0 4 6]
(3,)

hstack:
[9 5 0 0 4 6]
(6,)

concatenate:
[9 5 0 0 4 6]
(6,)

check:
True

column_stack reshaped:
[9 5 0 0 4 6]
(6,)

check:
True



### 2D array concatenate

In [5]:
# Creates two 2D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]

In [6]:
# Concatenates 2D arrays along first axis,
# which is equivalent to vertical or row stack.
z = [np.vstack((x, y)),
     np.row_stack((x, y)),
     np.concatenate((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', np.all(z[0] == z[2]), '',
      sep='\n')

1:
[[5 3 0 2]
 [6 8 0 3]
 [2 1 6 2]]
(3, 4)

2:
[[3 8 0 3]
 [1 7 9 7]
 [4 5 9 9]]
(3, 4)

vstack:
[[5 3 0 2]
 [6 8 0 3]
 [2 1 6 2]
 [3 8 0 3]
 [1 7 9 7]
 [4 5 9 9]]
(6, 4)

row_stack:
[[5 3 0 2]
 [6 8 0 3]
 [2 1 6 2]
 [3 8 0 3]
 [1 7 9 7]
 [4 5 9 9]]
(6, 4)

concatenate:
[[5 3 0 2]
 [6 8 0 3]
 [2 1 6 2]
 [3 8 0 3]
 [1 7 9 7]
 [4 5 9 9]]
(6, 4)

check:
True



In [7]:
# Concatenates 2D arrays along second axis,
# which is equivalent to horisontal or column stack.
z = [np.hstack((x, y)),
     np.column_stack((x, y)),
     np.concatenate((x, y), axis=1)]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', np.all(z[0] == z[2]),
      sep='\n')

1:
[[5 3 0 2]
 [6 8 0 3]
 [2 1 6 2]]
(3, 4)

2:
[[3 8 0 3]
 [1 7 9 7]
 [4 5 9 9]]
(3, 4)

hstack:
[[5 3 0 2 3 8 0 3]
 [6 8 0 3 1 7 9 7]
 [2 1 6 2 4 5 9 9]]
(3, 8)

column_stack:
[[5 3 0 2 3 8 0 3]
 [6 8 0 3 1 7 9 7]
 [2 1 6 2 4 5 9 9]]
(3, 8)

concatenate:
[[5 3 0 2 3 8 0 3]
 [6 8 0 3 1 7 9 7]
 [2 1 6 2 4 5 9 9]]
(3, 8)

check:
True


### 3D array concatenate

In [8]:
# Creates two 3D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, (2, 3, 4)
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]

In [9]:
# Concatenates 3D arrays along first axis,
# which is equivalent to vertical or row stack.
z = [np.vstack((x, y)),
     np.row_stack((x, y)),
     np.concatenate((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', np.all(z[0] == z[2]),
      sep='\n')

1:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]]]
(2, 3, 4)

2:
[[[8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(2, 3, 4)

vstack:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]]

 [[8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(4, 3, 4)

row_stack:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]]

 [[8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(4, 3, 4)

concatenate:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]]

 [[8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(4, 3, 4)

check:
True


In [10]:
# Concatenates 3D arrays along second axis,
# which is equivalent to horisontal or column stack.
z = [np.hstack((x, y)),
     np.column_stack((x, y)),
     np.concatenate((x, y), axis=1)]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'column_stack:', z[1], z[1].shape, '',
      'concatenate:', z[2], z[2].shape, '',
      'check:', np.all(z[0] == z[2]),
      sep='\n')

1:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]]]
(2, 3, 4)

2:
[[[8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(2, 3, 4)

hstack:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]
  [8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]
  [4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(2, 6, 4)

column_stack:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]
  [8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]
  [4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(2, 6, 4)

concatenate:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]
  [8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]
  [4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(2, 6, 4)

check:
True


In [11]:
# Concatenates 3D arrays along third axis.
z = np.concatenate((x, y), axis=2)

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'concatenate:', z, z.shape, '',
      'check 1:', np.all(x == z[...,:x.shape[2]]), '',
      'check 2:', np.all(y == z[...,y.shape[2]:]),
      sep='\n')

1:
[[[4 4 2 0]
  [0 1 1 2]
  [3 0 2 2]]

 [[7 5 2 7]
  [5 1 2 5]
  [9 4 2 2]]]
(2, 3, 4)

2:
[[[8 3 8 3]
  [9 8 0 4]
  [5 8 8 5]]

 [[4 3 9 8]
  [5 5 1 5]
  [9 2 8 7]]]
(2, 3, 4)

concatenate:
[[[4 4 2 0 8 3 8 3]
  [0 1 1 2 9 8 0 4]
  [3 0 2 2 5 8 8 5]]

 [[7 5 2 7 4 3 9 8]
  [5 1 2 5 5 5 1 5]
  [9 4 2 2 9 2 8 7]]]
(2, 3, 8)

check 1:
True

check 2:
True
