# Stacking together different arrays

## newaxis object
* If a dimension is given as **-1** in a reshaping operation,
  the other dimensions are automatically calculated.
* Each **newaxis** object in the selection tuple
  serves to expand the dimensions of the resulting selection
  by one unit-length dimension.
  The added dimension is the position of the **newaxis** object
  in the selection tuple.

In [1]:
import numpy as np
from numpy import newaxis

In [2]:
# Creates two 1D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, 3
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]

In [3]:
# Stacks two 1D arrays in verticle direction,
# using numpy.vstack, np.row_stack
# and concatenate functions.
z = [np.vstack((x, y)),
     # which works just like
     np.row_stack((x, y)),
     # or
     # np.concatenate((x.reshape(1, -1), y.reshape(1, -1))),
     # or
     np.concatenate((x[newaxis,:], y[newaxis,:]))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'concatenate reshaped:', z[2], z[2].shape, '',
      sep='\n')

1:
[8 7 9]
(3,)

2:
[8 1 7]
(3,)

vstack:
[[8 7 9]
 [8 1 7]]
(2, 3)

row_stack:
[[8 7 9]
 [8 1 7]]
(2, 3)

concatenate reshaped:
[[8 7 9]
 [8 1 7]]
(2, 3)



In [4]:
# Stacks two 1D arrays in horisontal direction,
# using numpy.vstack, np.row_stack
# and concatenate functions.
z = [np.hstack((x, y)),
     # Which works just like
     np.concatenate((x, y)),
     # or
     # np.ravel(np.column_stack((x.reshape(1, -1), y.reshape(1, -1)))),
     # or
     np.ravel(np.column_stack((x[newaxis,:], y[newaxis,:])))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'hstack:', z[0], z[0].shape, '',
      'concatenate:', z[1], z[1].shape, '',
      'column_stack reshape:', z[2], z[2].shape, '',
      sep='\n')

1:
[8 7 9]
(3,)

2:
[8 1 7]
(3,)

hstack:
[8 7 9 8 1 7]
(6,)

concatenate:
[8 7 9 8 1 7]
(6,)

column_stack reshape:
[8 7 9 8 1 7]
(6,)

