# Stacking together different arrays

## newaxis object
* Each **newaxis** object in the selection tuple
  serves to expand the dimensions of the resulting selection
  by one unit-length dimension.
* The added dimension is the position
  of the **newaxis** object in the selection tuple.

In [1]:
import numpy as np
from numpy import newaxis

In [2]:
# Creates two 1D arrays of the same shape,
# containig random integers in the range from 0 to 9.
n, s = 2, 3
x, y = [np.array(np.floor(10 * np.random.random(s)),
                 dtype=int)
        for _ in range(n)]

In [3]:
# Applies stack functions to 1D arrays.
z = [np.vstack((x, y)),
     np.row_stack((x, y)),
     np.hstack((x, y)),
     np.column_stack((x, y))]

print('1:', x, x.shape, '',
      '2:', y, y.shape, '',
      'vstack:', z[0], z[0].shape, '',
      'row_stack:', z[1], z[1].shape, '',
      'hstack:', z[2], z[2].shape, '',
      'column_stack:', z[3], z[3].shape, '',
      sep='\n')

1:
[6 0 9]
(3,)

2:
[7 2 7]
(3,)

vstack:
[[6 0 9]
 [7 2 7]]
(2, 3)

row_stack:
[[6 0 9]
 [7 2 7]]
(2, 3)

hstack:
[6 0 9 7 2 7]
(6,)

column_stack:
[[6 7]
 [0 2]
 [9 7]]
(3, 2)



In [4]:
# Increases the dimension of the 1D arrays
# by adding the first axis vie newaxis object,
# after that applies stack functions.
x1 = x[newaxis,:]
y1 = y[newaxis,:]
z1 = [np.vstack((x1, y1)),
      np.row_stack((x1, y1)),
      np.hstack((x1, y1)),
      np.column_stack((x1, y1))]

print('1:', x1, x1.shape, '',
      '2:', y1, y1.shape, '',
      'vstack:', z1[0], z1[0].shape, '',
      'row_stack:', z1[1], z1[1].shape, '',
      'hstack:', z1[2], z1[2].shape, '',
      'column_stack:', z1[3], z1[3].shape, '',
      sep='\n')

1:
[[6 0 9]]
(1, 3)

2:
[[7 2 7]]
(1, 3)

vstack:
[[6 0 9]
 [7 2 7]]
(2, 3)

row_stack:
[[6 0 9]
 [7 2 7]]
(2, 3)

hstack:
[[6 0 9 7 2 7]]
(1, 6)

column_stack:
[[6 0 9 7 2 7]]
(1, 6)



In [5]:
# Increases the dimension of the 1D arrays
# by adding the second axis vie newaxis object,
# after that applies stack functions.
x1 = x[:,newaxis]
y1 = y[:,newaxis]
z1 = [np.vstack((x1, y1)),
      np.row_stack((x1, y1)),
      np.hstack((x1, y1)),
      np.column_stack((x1, y1))]

print('1:', x1, x1.shape, '',
      '2:', y1, y1.shape, '',
      'vstack:', z1[0], z1[0].shape, '',
      'row_stack:', z1[1], z1[1].shape, '',
      'hstack:', z1[2], z1[2].shape, '',
      'column_stack:', z1[3], z1[3].shape, '',
      sep='\n')

1:
[[6]
 [0]
 [9]]
(3, 1)

2:
[[7]
 [2]
 [7]]
(3, 1)

vstack:
[[6]
 [0]
 [9]
 [7]
 [2]
 [7]]
(6, 1)

row_stack:
[[6]
 [0]
 [9]
 [7]
 [2]
 [7]]
(6, 1)

hstack:
[[6 7]
 [0 2]
 [9 7]]
(3, 2)

column_stack:
[[6 7]
 [0 2]
 [9 7]]
(3, 2)

