# Splitting one array into several smaller ones

## Horisontal splitting
* **numpy.hsplit** splits an array
  into multiple sub-arrays horizontally (column-wise).
* With a higher dimensional array the split
  is still along the second axis.

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Shape Manipulation](https://numpy.org/doc/1.17/user/quickstart.html#shape-manipulation) >>  
[Splitting one array into several smaller ones](https://numpy.org/doc/1.17/user/quickstart.html#splitting-one-array-into-several-smaller-ones)

In [1]:
import numpy as np
from numpy import newaxis


### 1D array splitting

In [2]:
# Creates 1D ndarray,
# using numpy.arange function.
x_min, x_max, x_step = 1, 12, 1  
x = np.arange(start=x_min,
              stop=x_max + x_step,
              step=x_step)


In [3]:
# Splits 1D array,
# using numpy.hsplit, into parts.
# Sets a list of parts.
p = [2, 3, 4]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.hsplit(x, _) for _ in p]

print(x, '',
      'hsplit:',
      sep='\n', end='\n\n')
for _ in y:
    print(f'parts: {len(_)}', _,
          sep='\n', end='\n\n')

# Stacks back 1D arrays,
# using numpy.hstack function.
z = [np.hstack(_) for _ in y]

print('hstack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 1D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_) for _ in y]

print('concatenate:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 1D arrays,
# using numpy.column_stack function.
z = [np.column_stack(_) for _ in y]

print('column_stack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 1D arrays,
# using numpy.column_stack function
# together with shape manipulation.
z = [np.ravel(np.column_stack(np.array(_)[:,newaxis,:]))
     for _ in y]

print('column_stack reshaped:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')


[ 1  2  3  4  5  6  7  8  9 10 11 12]

hsplit:

parts: 2
[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

parts: 3
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

parts: 4
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

hstack:

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

concatenate:

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

column_stack:

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

column_stack reshaped:

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]



In [4]:
# Splits 1D array,
# using numpy.hsplit, after columns.
# Sets a list of column indexes lists.
c = [[6],
     [4, 8],
     [3, 6, 9],
     [1, 3, 6, 9, 11]]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.hsplit(x, _) for _ in c]

print(x, '',
      'hsplit:',
      sep='\n', end='\n\n')
for _ in range(len(y)):
    print(f'columns: {c[_]}', y[_],
          sep='\n', end='\n\n')

# Stack back 1D arrays,
# using numpy.hstack function.
z = [np.hstack(_) for _ in y]

print('hstack', end='\n\n')   
for _ in z:
    print(_, end='\n\n')
    
# Stack back 1D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_) for _ in y]

print('concatenate', end='\n\n')   
for _ in z:
    print(_, end='\n\n')


[ 1  2  3  4  5  6  7  8  9 10 11 12]

hsplit:

columns: [6]
[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

columns: [4, 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

columns: [3, 6, 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

columns: [1, 3, 6, 9, 11]
[array([1]), array([2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11]), array([12])]

hstack

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

concatenate

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]



### 2D array splitting


In [5]:
# Creates 1D ndarray
# and reshapes it, making 2D ndarray.
x_shape = 3, 6
x_min, x_step = 1, 1
x_max = x_min + x_shape[0] * x_shape[1]
x = np.arange(start=x_min, stop=x_max, step=x_step)
x.shape = x_shape


In [6]:
# Splits 2D array,
# using numpy.hsplit, into parts.
# Sets a list of parts.
p = [2, 3]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.hsplit(x, _) for _ in p]

print(x, x.shape, '',
      'hsplit:',
      sep='\n', end='\n\n')
for _ in y:
    print(f'parts: {len(_)}', _,
          sep='\n', end='\n\n')

# Stacks back 2D arrays,
# using numpy.hstack function.
z = [np.hstack(_) for _ in y]

print('hstack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 2D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_, axis=1) for _ in y]

print('concatenate:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 2D arrays,
# using numpy.column_stack function.
z = [np.column_stack(_) for _ in y]

print('column_stack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')
    

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)

hsplit:

parts: 2
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])]

parts: 3
[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]

hstack:

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

concatenate:

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

column_stack:

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]



In [7]:
# Split 2D array,
# using numpy.hsplit, after columns.
# Sets a list of column indexes lists.
c = [[3],
     [2, 4],
     [1, 3]]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.hsplit(x, _) for _ in c]

print(x, x.shape, '',
      'hsplit:',
      sep='\n', end='\n\n')
for _ in range(len(y)):
    print(f'columns: {c[_]}', y[_],
          sep='\n', end='\n\n')

# Stack back 2D arrays,
# using numpy.hstack function.
z = [np.hstack(_) for _ in y]

print('hstack', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stack back 2D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_, axis=1) for _ in y]

print('concatenate', end='\n\n')   
for _ in z:
    print(_, end='\n\n')


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)

hsplit:

columns: [3]
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])]

columns: [2, 4]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]

columns: [1, 3]
[array([[ 1],
       [ 7],
       [13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])]

hstack

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

concatenate

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]



### 3D array splitting


In [8]:
# Creates 1D ndarray
# and reshapes it, making 2D ndarray.
x_shape = 2, 6, 3
x_min, x_step = 1, 1
x_max = x_min + x_shape[0] * x_shape[1] * x_shape[2]
x = np.arange(start=x_min, stop=x_max, step=x_step)
x.shape = x_shape


In [9]:
# Splits 3D array,
# using numpy.hsplit, into parts.
# Sets a list of parts.
p = [2, 3]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.hsplit(x, _) for _ in p]

print(x, x.shape, '',
      'hsplit:',
      sep='\n', end='\n\n')
for _ in y:
    print(f'parts: {len(_)}', _,
          sep='\n', end='\n\n')

# Stacks back 3D arrays,
# using numpy.hstack function.
z = [np.hstack(_) for _ in y]

print('hstack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 3D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_, axis=1) for _ in y]

print('concatenate:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 3D arrays,
# using numpy.column_stack function.
z = [np.column_stack(_) for _ in y]

print('column_stack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
(2, 6, 3)

hsplit:

parts: 2
[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]]), array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])]

parts: 3
[array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[19, 20, 21],
        [22, 23, 24]]]), array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[25, 26, 27],
        [28, 29, 30]]]), array([[[13, 14, 15],
        [16, 17, 18]],

       [[31, 32, 33],
        [34, 35, 36]]])]

hstack:

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 1

In [10]:
# Split 3D array,
# using numpy.hsplit, after columns.
# Sets a list of column indexes lists.
c = [[3],
     [2, 4],
     [1, 3]]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.hsplit(x, _) for _ in c]

print(x, x.shape, '',
      'hsplit:',
      sep='\n', end='\n\n')
for _ in range(len(y)):
    print(f'columns: {c[_]}', y[_],
          sep='\n', end='\n\n')

# Stack back 3D arrays,
# using numpy.hstack function.
z = [np.hstack(_) for _ in y]

print('hstack', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stack back 3D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_, axis=1) for _ in y]

print('concatenate', end='\n\n')   
for _ in z:
    print(_, end='\n\n')


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
(2, 6, 3)

hsplit:

columns: [3]
[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]]), array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])]

columns: [2, 4]
[array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[19, 20, 21],
        [22, 23, 24]]]), array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[25, 26, 27],
        [28, 29, 30]]]), array([[[13, 14, 15],
        [16, 17, 18]],

       [[31, 32, 33],
        [34, 35, 36]]])]

columns: [1, 3]
[array([[[ 1,  2,  3]],

       [[19, 20, 21]]]), array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[22, 23, 24],
        [25, 26, 27]]]), array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       