# Splitting one array into several smaller ones

## Verticle Splitting
* **numpy.vsplit** splits along the vertical axis.
* **vsplit** only works on arrays of 2 or more dimensions.

In [1]:
import numpy as np

In [2]:
# Creates 1D ndarray
# and reshapes it, making 2D ndarray.
x_shape = 6, 3
x_min, x_step = 1, 1
x_max = x_min + x_shape[0] * x_shape[1]
x = np.arange(start=x_min, stop=x_max, step=x_step)
x.shape = x_shape

In [3]:
# Splits 2D array,
# using numpy.vsplit, into parts.
# Sets a list of parts.
p = [2, 3]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.vsplit(x, _) for _ in p]

print(x, x.shape, '',
      'vsplit:',
      sep='\n', end='\n\n')
for _ in y:
    print(f'parts: {len(_)}', _,
          sep='\n', end='\n\n')

# Stacks back 2D arrays,
# using numpy.hstack function.
z = [np.vstack(_) for _ in y]

print('vstack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 2D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_) for _ in y]

print('concatenate:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stacks back 2D arrays,
# using numpy.row_stack function.
z = [np.row_stack(_) for _ in y]

print('row_stack:', end='\n\n')   
for _ in z:
    print(_, end='\n\n')    

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)

vsplit:

parts: 2
[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]

parts: 3
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]

vstack:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

concatenate:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

row_stack:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]



In [4]:
# Split 2D array,
# using numpy.vsplit, after rows.
# Sets list of row indexes lists.
c = [[3],
     [2, 4],
     [1, 3]]
# Creates a list of ndarray lists
# being results of splitting.
y = [np.vsplit(x, _) for _ in c]

print(x, x.shape, '',
      'vsplit:',
      sep='\n', end='\n\n')
for _ in range(len(y)):
    print(f'rows: {c[_]}', y[_],
          sep='\n', end='\n\n')

# Stack back 2D arrays,
# using numpy.vstack function.
z = [np.vstack(_) for _ in y]

print('vstack', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

# Stack back 2D arrays,
# using numpy.concatenate function.
z = [np.concatenate(_) for _ in y]

print('concatenate', end='\n\n')   
for _ in z:
    print(_, end='\n\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)

vsplit:

rows: [3]
[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]

rows: [2, 4]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]

rows: [1, 3]
[array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]

vstack

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

concatenate

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

