# No Copy at All

* Simple assignments make no copy
  of array objects or of their data.
* Python passes mutable objects as references,
  so function calls make no copy.

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Copies and Views](https://numpy.org/doc/1.17/user/quickstart.html#copies-and-views) >>  
[No Copy at All](https://numpy.org/doc/1.17/user/quickstart.html#no-copy-at-all)

In [1]:
import numpy as np


###  Simple assignment


In [2]:
# Creates an ndarray object.
x = np.arange(12)
print(x)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
# Makes a simple assignment,
# herewith no new object is created.
y = x
print(# These are two names for the same ndarray object.
      y is x,
      # id is a unique identifier of an object.
      id(y) == id(x),
      y,
      sep='\n')


True
True
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
# Changes the shape of ndarray object,
# using alternative name.
y.shape = 3, 4
print(x, x.shape, sep='\n')


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


### Passing an argument to a function

In [5]:
def get_id(x):
    """Returns object id."""
    return id(x)


print(id(x),
      # Passes ndarray object to function as reference.
      get_id(x),
      id(x) == get_id(x),
      sep='\n')


139869576590080
139869576590080
True
