# View or Shallow Copy

* Different array objects can share the same data.
* The **view** method creates a new array object
  that looks at the same data.
* Slicing an array returns a **view** of it.  

## Links
[NumPy v1.17 Manual](https://numpy.org/doc/1.17/index.html) >>  
[NumPy User Guide](https://numpy.org/doc/1.17/user/index.html) >>  
[Quickstart tutorial](https://numpy.org/doc/1.17/user/quickstart.html#) >>  
[Copies and Views](https://numpy.org/doc/1.17/user/quickstart.html#copies-and-views) >>  
[View or Shallow Copy](https://numpy.org/doc/1.17/user/quickstart.html#view-or-shallow-copy)

In [1]:
import numpy as np


### No copy


In [2]:
# Creates ndarray object and reshapes it.
x_shape = 3, 4
x_start, x_step = 1, 1
x = np.arange(start=x_start,
              stop=x_start + x_shape[0] * x_shape[1],
              step=x_step)
x.shape = x_shape

print(x,
      x.shape,
      # The array owns the memory it uses.
      x.flags.owndata,
      sep='\n', end='\n')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True


In [3]:
# Creates a reference to ndarray object
# and reshapes it, using alternative name.
y = x
y.shape = y.shape[::-1]
# Which is just transposion,
# it works like
# y.resize(y.shape[::-1])

print(# There are two names for the same ndarray object.
      y is x,
      # id is a unique identifier of an object.
      id(y) == id(x), '',
      x, x.shape,    
      sep='\n')


True
True

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [4]:
# Reshape ndarray object again,
# using alternative name.
y.shape = y.size
# Which is just transposion,
# it works like
# y.resize(y.shape[::-1])

print(# This is still the same object.
      y is x,
      id(y) == id(x), '',
      x, x.shape,
      sep='\n')


True
True

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


### Shallow copy


In [5]:
# Shares the ndarray object, using view method.
y = x.view()

print(# These are two different objects,
      # whose have different id.
      y is x, '',
      id(x), id(y), id(y) == id(x), '',
      # The array owns the memory it uses,
      # while view object borrows memorry from it.
      x.flags.owndata, y.flags.owndata, '',
      # One object is a view of the data owned by another.
      y.base is x,
      sep='\n')


False

140355651586128
140355651658016
False

True
False

True


In [6]:
# Reshapes ndarray object and its view object.
x.shape = 3, x.size // 3
y.shape = 4, y.size // 4

print(# Data owner.
      id(x), x, x.shape, x.flags.owndata, '',
      # Data borrower.
      id(y), y, y.shape, y.flags.owndata, '',
      # One object is a view of the data owned by another.
      y.base is x,
      sep='\n')


140355651586128
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651658016
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
False

True


### Shallow copy changing


In [7]:
# Changing data
# by elementwise accessing a shallow copy
# makes it new data owner.

# Makes a deep copy.
y = x.copy()
# Makes a shallow copy and reshapes it.
z = y.view()
z.shape = z.size

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n', end='\n\n')

# Changes a shallow copy.
z = -z

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n')


140355651658816
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651658016
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
False

True

140355651658816
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651658416
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12]
(12,)
True

False


In [8]:
# Changing data
# by index accessing a shallow copy
# changes data owner itself.

# Makes a deep copy.
y = x.copy()
# Makes a shallow copy and reshape it.
z = y.view()
z.shape = z.size

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n', end='\n\n')

# Changes a shallow copy.
z[0] = z[-1] = 0

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n')


140355651658016
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651658816
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
False

True

140355651658016
[[ 0  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11  0]]
(3, 4)
True

140355651658816
[ 0  2  3  4  5  6  7  8  9 10 11  0]
(12,)
False

True


In [9]:
# Changing data
# by index accessing a shallow copy
# changes data owner itself.

# Makes a deep copy.
y = x.copy()
# Makes a shallow copy.
z = y.view()

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n', end='\n\n')

# Changes a shallow copy.
z[0] = z[-1] = 0

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n')


140355651659776
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651659296
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
False

True

140355651659776
[[0 0 0 0]
 [5 6 7 8]
 [0 0 0 0]]
(3, 4)
True

140355651659296
[[0 0 0 0]
 [5 6 7 8]
 [0 0 0 0]]
(3, 4)
False

True


### Shallow copy by slicing


In [10]:
# Changing data by slicing
# changes data owner itself.

# Makes a deep copy.
y = x.copy()
# Slicing an array returns a shallow copy of it.
z = y[1:-1,1:-1]

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n', end='\n\n')

# Changes slice.
z[:,:] = 0

print(id(y), y, y.shape, y.flags.owndata, '',
      id(z), z, z.shape, z.flags.owndata, '',
      z.base is y,
      sep='\n')


140355651658016
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651659696
[[6 7]]
(1, 2)
False

True

140355651658016
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9 10 11 12]]
(3, 4)
True

140355651659696
[[0 0]]
(1, 2)
False

True
