# Deep Copy

* The **copy** method makes a complete copy of the array and its data.
* Sometimes **copy** should be called after slicing
  if the original array is not required anymore.

In [1]:
import numpy as np

### Deep copy vs shallow copy 


In [2]:
# Creates ndarray object and reshapes it.
x_shape = 4, 4
x_start, x_step = 1, 1
x = np.arange(start=x_start,
              stop=x_start + x_shape[0] * x_shape[1],
              step=x_step)
x.shape = x_shape

print(x, x.shape,
      sep='\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [3]:
# Makes a deep copy of ndarray,
# using copy method,
# and changes it, using slicing.
y = x.copy()
y[1:-1,1:-1] = 0

print(x is y, y.base is x, '',
      id(x), x, x.shape, x.flags.owndata, '',
      id(y), y, y.shape, y.flags.owndata, '',
      sep='\n')

False
False

140445456457520
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
True

140445035837040
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]
(4, 4)
True



In [4]:
# Makes a shallow copy of ndarray,
# using view method,
# and changes it, using slicing.
y = x.view()
y[1:-1,1:-1] = 0

print(x is y, y.base is x, '',
      id(x), x, x.shape, x.flags.owndata, '',
      id(y), y, y.shape, y.flags.owndata, '',
      sep='\n')

False
True

140445456457520
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]
(4, 4)
True

140445035837600
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]
(4, 4)
False



### Deep Copy After Slicing

In [5]:
# Deep copy should be made
# when constructing with slicing.

# Creates a huge ndarray.
x_size = int(1e8)
x = np.arange(x_size)
print(x)

# Makes a deep copy after slicing.
y = x[:100].copy()
# The memory of initial ndarray can be released.
del x
print(y)

[       0        1        2 ... 99999997 99999998 99999999]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
