# [Broadcasting rules][broadcasting_rules]

* The **first rule** of broadcasting is that
  if all input arrays do not have the same number of dimensions,
  a “1” will be repeatedly prepended
  to the shapes of the smaller arrays
  until all the arrays have the same number of dimensions.
* The **second rule** of broadcasting ensures
  that arrays with a size of 1 along a particular dimension act as
  if they had the size of the array
  with the largest shape along that dimension.
  The value of the array element is assumed to be the same
  along that dimension for the “broadcast” array.  
  In other words, two dimensions are compatible when
  * they are equal, or
  * one of them is 1.
* If these conditions are not met, an exception is thrown,
  indicating that the arrays have incompatible shapes.
* After application of the broadcasting rules,
  the sizes of all arrays must match.
* When operating on two arrays,
  NumPy compares their shapes element-wise.
  It starts with the trailing dimensions
  and works its way forward.

## Links
[NumPy Manual][manual] >>  
[NumPy User Guide][user_guide] >> 
* [Quickstart tutorial][tutorial] >>  
  [Less Basic][lessbasic] >>  
  [Broadcasting rules][broadcasting_rules]
* [NumPy basics][basics] >>  
  [Broadcasting][broadcasting]

[comment]: # (tags)
[manual]: https://numpy.org/devdocs/
[user_guide]: https://numpy.org/devdocs/user/index.html
[tutorial]: https://numpy.org/devdocs/user/quickstart.html#
[lessbasic]: https://numpy.org/devdocs/user/quickstart.html#less-basic
[broadcasting_rules]: https://numpy.org/devdocs/user/quickstart.html#broadcasting-rules
[basics]: https://numpy.org/devdocs/user/basics.html
[broadcasting]: https://numpy.org/devdocs/user/basics.broadcasting.html

In [1]:
import numpy as np


In [2]:
def foo(i, j):
    """Adds axis indexes of supposed 2D array
    multiplied by the corresponding powers of ten.

    Parameters
    ----------
    i : int
        Supposed first axis index,
        multiplying by 10.
    j : int
        Supposed second axis index,
        multiplying by 1.
    
    Returns
    _______
    out : int
        10 * i + j
    """
    return 10 * i + j


def bar(i, j, k):
    """Adds axis indexes of supposed 3D array
    multiplied by the corresponding powers of ten.

    Parameters
    ----------
    i : int
        Supposed first axis index,
        multiplying by 100.
    j : int
        Supposed second axis index,
        multiplying by 10.
    k : int
        Supposed third axis index,
        multiplying by 1.
    
    Returns
    _______
    out : int
        100 * i + 10 * j + k
    """
    return 100 * i + 10 * j + k



### 2D array to 3D

#### Broadcasting axis: first
 array  | shape
:------:|----------:
 x      | 2 x 3 x 4
 y      |     3 x 4
 result | 2 x 3 x 4

In [3]:
# Creates two arrays,
# having different shapes.
# The first one is 3D and full of zeros.
# The second is 2D and made from function.
x_shape = 2, 3, 4
y_shape =    3, 4
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(foo, shape=y_shape, dtype=int)
# Adds two arrays, using broadcasting.
z = x + y

# What would work also
# if the second array were 3D
# but had a restricted shape.
y1_shape = list(y_shape)
y1_shape[0:0] = [1]
y1 = np.fromfunction(lambda i, j, k: foo(j, k),
                     shape=y1_shape, dtype=int)
z1 = x + y1

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape, '',
      'y1:', y1, y1.shape, '',
      'z1:', z1, z1.shape, '',
      'check: ', z == z1,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
(3, 4)

z:
[[[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]]
(2, 3, 4)

y1:
[[[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]]
(1, 3, 4)

z1:
[[[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]]
(2, 3, 4)

check: 
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


#### Broadcasting axis: first and third
 array  | shape
:------:|----------:
 x      | 2 x 3 x 4
 y      |     3 x 1
 result | 2 x 3 x 4

In [4]:
# Creates two arrays,
# having different shapes.
# The first one is 3D and full of zeros.
# The second is 2D and made from function.
x_shape = 2, 3, 4
y_shape =    3, 1
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(foo, shape=y_shape, dtype=int)
# Adds two arrays, using broadcasting.
z = x + y

# What would work also
# if the second array were 3D
# but had a restricted shape.
y1_shape = list(y_shape)
y1_shape[0:0] = [1]
y1 = np.fromfunction(lambda i, j, k: foo(j, k),
                     shape=y1_shape, dtype=int)
z1 = x + y1

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape, '',
      'y1:', y1, y1.shape, '',
      'z1:', z1, z1.shape, '',
      'check:', z == z1,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[ 0]
 [10]
 [20]]
(3, 1)

z:
[[[ 0  0  0  0]
  [10 10 10 10]
  [20 20 20 20]]

 [[ 0  0  0  0]
  [10 10 10 10]
  [20 20 20 20]]]
(2, 3, 4)

y1:
[[[ 0]
  [10]
  [20]]]
(1, 3, 1)

z1:
[[[ 0  0  0  0]
  [10 10 10 10]
  [20 20 20 20]]

 [[ 0  0  0  0]
  [10 10 10 10]
  [20 20 20 20]]]
(2, 3, 4)

check:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


#### Broadcasting axis: first and second
 array  | shape
:------:|----------:
 x      | 2 x 3 x 4
 y      |     1 x 4
 result | 2 x 3 x 4

In [5]:
# Creates two arrays,
# having different shapes.
# The first one is 3D and full of zeros.
# The second is 2D and made from function.
x_shape = 2, 3, 4
y_shape =    1, 4
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(foo, shape=y_shape, dtype=int)
# Adds two arrays, using broadcasting.
z = x + y

# What would work also
# if the second array were 3D
# but had a restricted shape.
y1_shape = list(y_shape)
y1_shape[0:0] = [1]
y1 = np.fromfunction(lambda i, j, k: foo(j, k),
                     shape=y1_shape, dtype=int)
z1 = x + y1

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape, '',
      'y1:', y1, y1.shape, '',
      'z1:', z1, z1.shape, '',
      'check:', z == z1,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[0 1 2 3]]
(1, 4)

z:
[[[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
(2, 3, 4)

y1:
[[[0 1 2 3]]]
(1, 1, 4)

z1:
[[[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
(2, 3, 4)

check:
[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


### 3D arrays to 3D

#### No broadcasting
 array  | shape
:------:|----------:
 x      | 2 x 3 x 4
 y      | 2 x 3 x 4
 result | 2 x 3 x 4

In [6]:
# Creates two 3D arrays,
# having the same shapes.
# The first one is full of zeros.
# The second is made from function.
x_shape = 2, 3, 4
y_shape = 2, 3, 4 
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(bar, shape=y_shape, dtype=int)
# Adds two arrays elemtwise.
z = x + y

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[[  0   1   2   3]
  [ 10  11  12  13]
  [ 20  21  22  23]]

 [[100 101 102 103]
  [110 111 112 113]
  [120 121 122 123]]]
(2, 3, 4)

z:
[[[  0   1   2   3]
  [ 10  11  12  13]
  [ 20  21  22  23]]

 [[100 101 102 103]
  [110 111 112 113]
  [120 121 122 123]]]
(2, 3, 4)


#### Broadcasting axis: third
 array  | shape
:------:|----------:
 x      | 3 x 4 x 5
 y      | 3 x 4 x 1
 result | 3 x 4 x 5

In [7]:
# Creates two 3D arrays,
# having different shapes.
# The first one is full of zeros.
# The second is made from function and
# has restricted shape.
x_shape = 2, 3, 4
y_shape = 2, 3, 1
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(bar, shape=y_shape, dtype=int)
# Adds two arrays, using broadcasting.
z = x + y

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[[  0]
  [ 10]
  [ 20]]

 [[100]
  [110]
  [120]]]
(2, 3, 1)

z:
[[[  0   0   0   0]
  [ 10  10  10  10]
  [ 20  20  20  20]]

 [[100 100 100 100]
  [110 110 110 110]
  [120 120 120 120]]]
(2, 3, 4)


#### Broadcasting axis: second
 array  | shape
:------:|----------:
 x      | 3 x 4 x 5
 y      | 3 x 1 x 5
 result | 3 x 4 x 5

In [8]:
# Creates two 3D arrays,
# having different shapes.
# The first one is full of zeros.
# The second is made from function and
# has restricted shape.
x_shape = 2, 3, 4
y_shape = 2, 1, 4
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(bar, shape=y_shape, dtype=int)
# Adds two arrays, using broadcasting.
z = x + y

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[[  0   1   2   3]]

 [[100 101 102 103]]]
(2, 1, 4)

z:
[[[  0   1   2   3]
  [  0   1   2   3]
  [  0   1   2   3]]

 [[100 101 102 103]
  [100 101 102 103]
  [100 101 102 103]]]
(2, 3, 4)


#### Broadcasting axis: first
 array  | shape
:------:|----------:
 x      | 3 x 4 x 5
 y      | 1 x 4 x 5
 result | 3 x 4 x 5

In [9]:
# Creates two 3D arrays,
# having different shapes.
# The first one is full of zeros.
# The second is made from function and
# has restricted shape.
x_shape = 2, 3, 4
y_shape = 1, 3, 4
x = np.zeros(shape=x_shape, dtype=int)
y = np.fromfunction(bar, shape=y_shape, dtype=int)
# Adds two arrays, using broadcasting.
z = x + y

print('x:', x, x.shape, '',
      'y:', y, y.shape, '',
      'z:', z, z.shape,
      sep='\n')


x:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
(2, 3, 4)

y:
[[[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]]
(1, 3, 4)

z:
[[[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [10 11 12 13]
  [20 21 22 23]]]
(2, 3, 4)
