# [Indexing with Arrays of Indices][indexing]

## 1D Array Indexing by an Array of Integers
* In addition to indexing by integers and slices,
  arrays can be indexed by arrays of integers.
* When the indexed array is multidimensional,
  a single array of indices refers to its first dimension.

## Links
[NumPy Manual][manual] >>  
[NumPy User Guide][user_guide] >>  
[Quickstart tutorial][tutorial] >>  
[Advanced indexing and index tricks][index_tricks] >>  
[Indexing with Arrays of Indices][indexing]

[comment]: #(tags)
[manual]: https://numpy.org/devdocs/
[user_guide]: https://numpy.org/devdocs/user/index.html
[tutorial]: https://numpy.org/devdocs/user/quickstart.html#
[index_tricks]: https://numpy.org/devdocs/user/quickstart.html#advanced-indexing-and-index-tricks
[indexing]: https://numpy.org/devdocs/user/quickstart.html#indexing-with-arrays-of-indices

In [1]:
import numpy as np


In [2]:
# Creates 1D array of squares.
x_min, x_max, x_step = 0, 10, 1
x = np.arange(start=x_min,
              stop=x_max + x_step,
              step=x_step)
x = x**2

print('x:', x, x.shape,
      sep='\n', end='\n\n')

print('{:>2} {:>3}'.format('k', 'x'))
for _ in range(len(x)):
    print(f'{_:>2} {x[_]:>3}')


x:
[  0   1   4   9  16  25  36  49  64  81 100]
(11,)

 k   x
 0   0
 1   1
 2   4
 3   9
 4  16
 5  25
 6  36
 7  49
 8  64
 9  81
10 100


### 1D by 1D

In [3]:
# Creates 1D array of random integers,
# which is the array of indices.
i_shape = 4,
i_low, i_high = 0, x.size
i=np.random.randint(low=i_low,
                    high=i_high,
                    size=i_shape)
# Creates 1D array
# indexed by 1D array of integers,
# which contrains the elements
# at specified positions.
y = x[i]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'y:', y, y.shape,
      sep='\n', end='\n\n')

print('{:>2} {:>2} {:>3}'.format('k', 'i', 'y'))
for _ in range(len(i)):
    print(f'{_:>2} {i[_]:>2} {y[_]:>3}')


x:
[  0   1   4   9  16  25  36  49  64  81 100]
(11,)

i:
[6 6 4 7]
(4,)

y:
[36 36 16 49]
(4,)

 k  i   y
 0  6  36
 1  6  36
 2  4  16
 3  7  49


### 1D by 2D

In [4]:
# Creates 2D array of random integers,
# which is the array of indices.
i_shape = 3, 4
i_low, i_high = 0, x.size
i=np.random.randint(low=i_low,
                    high=i_high,
                    size=i_shape)
# Creates 2D array
# indexed by 2D array of integers,
# which contrains the elements
# at specified positions.
y = x[i]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'y:', y, y.shape,
      sep='\n')


x:
[  0   1   4   9  16  25  36  49  64  81 100]
(11,)

i:
[[ 0  7  9 10]
 [ 7  4  4  3]
 [ 9  4  0  3]]
(3, 4)

y:
[[  0  49  81 100]
 [ 49  16  16   9]
 [ 81  16   0   9]]
(3, 4)
