# [Indexing with Arrays of Indices][indexing]

## 2D Array Indexing by Array of Integers

* In addition to indexing by integers and slices,
  arrays can be indexed by arrays of integers.
* When the indexed array is multidimensional,
  a single array of indices refers to its first dimension.

## Links
[NumPy Manual][manual] >>  
[NumPy User Guide][user_guide] >>  
[Quickstart tutorial][tutorial] >>  
[Fancy indexing and index tricks][index_tricks] >>  
[Indexing with Arrays of Indices][indexing]

[comment]: #(tags)
[manual]: https://numpy.org/devdocs/
[user_guide]: https://numpy.org/devdocs/user/index.html
[tutorial]: https://numpy.org/devdocs/user/quickstart.html#
[index_tricks]: https://numpy.org/devdocs/user/quickstart.html#fancy-indexing-and-index-tricks
[indexing]: https://numpy.org/devdocs/user/quickstart.html#indexing-with-arrays-of-indices

In [1]:
import numpy as np


In [2]:
# Creates 3D array containing
# square and cubic degrees.
x_min, x_max, x_step = 0, 10, 1
x = np.arange(start=x_min,
              stop=x_max + x_step,
              step=x_step)
x = np.array([x**2, x**3]).T

print('x:', x, x.shape,
      sep='\n', end='\n\n')

print('{:>2} {:>3} {:>4}'.format('x', 'x^2', 'x^3'))
for _ in range(len(x)):
    print(f'{_:>2} {x[_, 0]:>3} {x[_, 1]:>4}')


x:
[[   0    0]
 [   1    1]
 [   4    8]
 [   9   27]
 [  16   64]
 [  25  125]
 [  36  216]
 [  49  343]
 [  64  512]
 [  81  729]
 [ 100 1000]]
(11, 2)

 x x^2  x^3
 0   0    0
 1   1    1
 2   4    8
 3   9   27
 4  16   64
 5  25  125
 6  36  216
 7  49  343
 8  64  512
 9  81  729
10 100 1000


### 2D by 1D

In [3]:
# Creates 1D array of random integers,
# which is the array of indices.
i_shape = 3,
i_low, i_high = 0, x.shape[0]
i=np.random.randint(low=i_low,
                    high=i_high,
                    size=i_shape)
# Creates 2D array
# indexed by the array of integers,
# which contrains the elements
# at specified positions.
y = x[i]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'y:', y, y.shape,
      sep='\n', end='\n\n')

print('{:>2} {:>2} {:>3} {:>4}'.format('k', 'x', 'x^2', 'x^3'))
for _ in range(len(i)):
    print(f'{_:>2} {i[_]:>2} {y[_, 0]:>3} {y[_, 1]:>4}')


x:
[[   0    0]
 [   1    1]
 [   4    8]
 [   9   27]
 [  16   64]
 [  25  125]
 [  36  216]
 [  49  343]
 [  64  512]
 [  81  729]
 [ 100 1000]]
(11, 2)

i:
[7 7 5]
(3,)

y:
[[ 49 343]
 [ 49 343]
 [ 25 125]]
(3, 2)

 k  x x^2  x^3
 0  7  49  343
 1  7  49  343
 2  5  25  125


### 2D by 2D

In [4]:
# Creates 2D array of random integers,
# which is the array of indices.
i_shape = 3, 4
i_low, i_high = 0, x.shape[0]
i=np.random.randint(low=i_low,
                    high=i_high,
                    size=i_shape)
# Creates 3D array
# indexed by the array of integers,
# which contrains the elements
# at specified positions.
y = x[i]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'y:', y, y.shape,
      sep='\n', end='\n\n')


x:
[[   0    0]
 [   1    1]
 [   4    8]
 [   9   27]
 [  16   64]
 [  25  125]
 [  36  216]
 [  49  343]
 [  64  512]
 [  81  729]
 [ 100 1000]]
(11, 2)

i:
[[5 6 8 1]
 [6 7 4 5]
 [3 6 6 5]]
(3, 4)

y:
[[[ 25 125]
  [ 36 216]
  [ 64 512]
  [  1   1]]

 [[ 36 216]
  [ 49 343]
  [ 16  64]
  [ 25 125]]

 [[  9  27]
  [ 36 216]
  [ 36 216]
  [ 25 125]]]
(3, 4, 2)

