# [Indexing with Arrays of Indices][indexing]

* Arrays can be indexed by arrays of integers.
* When the indexed array a is multidimensional,
  a single array of indices refers to its first dimension.
* You can also give indexes for more than one dimension.
  In this case, the arrays of indices for each dimension
  must have the same shape.

## Links
[NumPy Manual][manual] >>  
[NumPy User Guide][user_guide] >>  
[Quickstart tutorial][tutorial] >>  
[Fancy indexing and index tricks][index_tricks] >>  
[Indexing with Arrays of Indices][indexing]

[comment]: #(tags)
[manual]: https://numpy.org/devdocs/
[user_guide]: https://numpy.org/devdocs/user/index.html
[tutorial]: https://numpy.org/devdocs/user/quickstart.html#
[index_tricks]: https://numpy.org/devdocs/user/quickstart.html#fancy-indexing-and-index-tricks
[indexing]: https://numpy.org/devdocs/user/quickstart.html#indexing-with-arrays-of-indices

In [1]:
import numpy as np


In [2]:
palette = np.array([[0,0,0],         # black
                    [255,0,0],       # red
                    [0,255,0],       # green
                    [0,0,255],       # blue
                    [255,255,255]])  # white

image = np.array([[0, 0, 0, 0],
                  [0, 1, 2, 0],
                  [0, 3, 4, 0],
                  [0, 0, 0, 0]])

plot = palette[image]

print('palette:', palette, palette.shape, '',
      'image:', image, image.shape, '',
      'palette[image]:', plot, plot.shape,
      sep='\n')


palette:
[[  0   0   0]
 [255   0   0]
 [  0 255   0]
 [  0   0 255]
 [255 255 255]]
(5, 3)

image:
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]
(4, 4)

palette[image]:
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
(4, 4, 3)
