# Indexing with Arrays of Indices

* Arrays can be indexed by arrays of integers.
* When the indexed array a is multidimensional,
  a single array of indices refers to its first dimension.
* You can also give indexes for more than one dimension.  
  In this case, the arrays of indices for each dimension
  must have the same shape.
* Naturally, you can put row and column arrays
  in a sequence (say a tuple)
  and then do the indexing with the sequence.  
  However, you can not do this by putting
  row and column arrays into an array,
  because this array will be interpreted
  as indexing the first dimension.

In [1]:
import numpy as np

In [2]:
# Creates 2D array.
x_shape = 5, 6
x_min, x_step = 1, 1
x_max = x_shape[0] * x_shape[1]
x = np.arange(start=x_min, stop=x_max + x_step,
              step=x_step)
x.shape = x_shape

print('x:', x, x.shape, sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)


### Indexing by 1D array

In [3]:
# Creates 1D array of row indeces.
i_shape = 3,
i_low, i_high = 0, x.shape[0]
i = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Creates 2D array by indexing,
# which is actually an array of rows.
y = x[i]
# It works just like the follows.
z = x[i,:]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'x[i]:', y, y.shape, '',
      'x[i,:]:', z, z.shape, '',
      'check:', np.all(y == z),      
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i:
[4 1 0]
(3,)

x[i]:
[[25 26 27 28 29 30]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]
(3, 6)

x[i,:]:
[[25 26 27 28 29 30]
 [ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]
(3, 6)

check:
True


In [4]:
# Creates 1D array of column indeces.
j_shape = 3,
j_low, i_high = 0, x.shape[0]
j = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Creates 2D array by indexing,
# which is actually
# a transposed array of columns.
y = x[:,j]

print('x:', x, x.shape, '',
      'j:', j, j.shape, '',
      'x[:,j]:', y, y.shape, '',
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

j:
[4 1 3]
(3,)

x[:,j]:
[[ 5  2  4]
 [11  8 10]
 [17 14 16]
 [23 20 22]
 [29 26 28]]
(5, 3)



### Indexing by 1D array and scalar

In [5]:
# Creates 1D array of row indeces.
i_shape = 3,
i_low, i_high = 0, x.shape[0]
i = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Sets column index,
# that is fixes it.
j_low, j_high = 0, x.shape[1]
j = np.random.randint(low=j_low, high=j_high)
# Creates 1D array by indexing,
# which contains values from one column.
y = x[i, j]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      f'j: {j}', '',
      'x[i, j]:', y, y.shape, '',
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i:
[4 3 3]
(3,)

j: 5

x[i, j]:
[30 24 24]
(3,)



In [6]:
# Sets row index,
# that is fixes it.
i_low, i_high = 0, x.shape[0]
i = np.random.randint(low=j_low, high=j_high)
# Creates 1D array of column indeces.
j_shape = 3,
j_low, j_high = 0, x.shape[1]
j = np.random.randint(low=j_low, high=j_high,
                      size=j_shape)
# Creates 1D array by indexing,
# which contains values from one row.
y = x[i, j]

print('x:', x, x.shape, '',
      f'i: {i}', '',
      'j:', j, j.shape, '',
      'x[i, j]:', y, y.shape, '',
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i: 4

j:
[5 4 3]
(3,)

x[i, j]:
[30 29 28]
(3,)



### Indexing by two 1D arrays

In [7]:
# Sets the shape of indeces arrays.
_shape = 3,
# Creates 1D array of row indeces.
i_low, i_high = 0, x.shape[0]
i_shape = _shape
i = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Creates 1D array of column indeces.
j_low, j_high = 0, x.shape[1]
j_shape = _shape
j = np.random.randint(low=j_low, high=j_high,
                      size=j_shape)
# Creates 1D array by indexing.
y = x[i, j]
# Which works just like the following.
n = i, j
# not
# n = np.array((i, j))
z = x[n]


print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'j:', j, j.shape, '',
      'x[i, j]:', y, y.shape, '',
      'i:', n, '',
      'x[i]:', z, z.shape, '',
      'check:', np.all(y == z),
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i:
[4 2 0]
(3,)

j:
[2 1 2]
(3,)

x[i, j]:
[27 14  3]
(3,)

i:
(array([4, 2, 0]), array([2, 1, 2]))

x[i]:
[27 14  3]
(3,)

check:
True


### Indexing  by 2D array and scalar

In [8]:
# Creates 2D array of row indeces.
i_shape = 3, 4
i_low, i_high = 0, x.shape[0]
i = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Sets column index,
# that is fixes it.
j_low, j_high = 0, x.shape[1]
j = np.random.randint(low=j_low, high=j_high)
# Creates 2D array by indexing,
# which contains values from one column. 
y = x[i, j]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      f'j: {j}', '',
      'x[i, j]:', y, y.shape, '',
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i:
[[0 3 3 0]
 [3 1 3 3]
 [4 4 4 2]]
(3, 4)

j: 1

x[i, j]:
[[ 2 20 20  2]
 [20  8 20 20]
 [26 26 26 14]]
(3, 4)



In [9]:
# Sets row index,
# that is fixes it.
i_low, i_high = 0, x.shape[0]
i = np.random.randint(low=j_low, high=j_high)
# Creates 2D array of column indeces.
j_shape = 3, 4
j_low, j_high = 0, x.shape[1]
j = np.random.randint(low=j_low, high=j_high,
                      size=j_shape)
# Creates 2D array by indexing,
# which contains values from one row.
y = x[i, j]

print('x:', x, x.shape, '',
      f'i: {i}', '',
      'j:', j, j.shape, '',
      'x[i, j]:', y, y.shape, '',
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i: 4

j:
[[2 4 5 4]
 [1 0 0 1]
 [4 4 2 3]]
(3, 4)

x[i, j]:
[[27 29 30 29]
 [26 25 25 26]
 [29 29 27 28]]
(3, 4)



### Indexing by 2D array

In [10]:
# Creates 2D array of row indeces.
i_shape = 2, 3 
i_low, i_high = 0, x.shape[0]
i = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Creates 3D array by indexing,
# which is actually
# an array of arrays of rows.
y = x[i]
# It works just like the follows.
z = x[i,:]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'x[i]:', y, y.shape, '',
      'x[i,:]:', z, z.shape, '',
      'check:', np.all(y == z),      
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i:
[[2 1 0]
 [0 2 2]]
(2, 3)

x[i]:
[[[13 14 15 16 17 18]
  [ 7  8  9 10 11 12]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  6]
  [13 14 15 16 17 18]
  [13 14 15 16 17 18]]]
(2, 3, 6)

x[i,:]:
[[[13 14 15 16 17 18]
  [ 7  8  9 10 11 12]
  [ 1  2  3  4  5  6]]

 [[ 1  2  3  4  5  6]
  [13 14 15 16 17 18]
  [13 14 15 16 17 18]]]
(2, 3, 6)

check:
True


In [11]:
# Creates 2D array of column indeces.
j_shape = 2, 3
j_low, i_high = 0, x.shape[0]
j = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Creates 3D array by indexing.
y = x[:,j]

print('x:', x, x.shape, '',
      'j:', j, j.shape, '',
      'x[:,j]:', y, y.shape, '',
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

j:
[[4 1 3]
 [4 0 0]]
(2, 3)

x[:,j]:
[[[ 5  2  4]
  [ 5  1  1]]

 [[11  8 10]
  [11  7  7]]

 [[17 14 16]
  [17 13 13]]

 [[23 20 22]
  [23 19 19]]

 [[29 26 28]
  [29 25 25]]]
(5, 2, 3)



### Indexing by two 2D arrays

In [12]:
# Sets the shape of indeces arrays.
_shape = 3, 4
# Creates 2D array of row indeces.
i_low, i_high = 0, x.shape[0]
i_shape = _shape
i = np.random.randint(low=i_low, high=i_high,
                      size=i_shape)
# Creates 2D array of column indeces.
j_low, j_high = 0, x.shape[1]
j_shape = _shape
j = np.random.randint(low=j_low, high=j_high,
                      size=j_shape)
# Creates 2D array by indexing.
y = x[i, j]
# Which works just like the following.
n = i, j
# not
# n = np.array((i, j))
z = x[n]

print('x:', x, x.shape, '',
      'i:', i, i.shape, '',
      'j:', j, j.shape, '',
      'x[i, j]:', y, y.shape, '',
      'i:', n, '',
      'x[i]:', z, z.shape, '',
      'check:', np.all(y == z),
      sep='\n')

x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
(5, 6)

i:
[[3 3 1 2]
 [1 3 3 4]
 [0 3 1 3]]
(3, 4)

j:
[[0 3 0 0]
 [0 3 0 1]
 [4 1 2 2]]
(3, 4)

x[i, j]:
[[19 22  7 13]
 [ 7 22 19 26]
 [ 5 20  9 21]]
(3, 4)

i:
(array([[3, 3, 1, 2],
       [1, 3, 3, 4],
       [0, 3, 1, 3]]), array([[0, 3, 0, 0],
       [0, 3, 0, 1],
       [4, 1, 2, 2]]))

x[i]:
[[19 22  7 13]
 [ 7 22 19 26]
 [ 5 20  9 21]]
(3, 4)

check:
True
