# Indexing with Arrays of Indices


## Assignment Using Indexing
* You can also use indexing with arrays as a target to assign to.
* However, when the list of indices contains repetitions,
  the assignment is done several times,
  leaving behind the last value.
* Otherwise, if you want to use Python’s incremention construct.
  Even though index occurs more than one in the list of indices,
  the corresponding element is only incremented once.

In [2]:
import numpy as np

### Assignment

In [3]:
# Creates 1D array,
# which is a target to assign to.
x_size = 10
x = np.arange(x_size)

print('target:', x,
      sep = '\n', end='\n\n')

# Creates 1D array of integers,
# which is an array of indeces.
i_low, i_high = 0, x.size
i_size = 4
i = np.random.randint(low=i_low, high=i_high,
                      size=i_size)
# Stupid way to provide
# a repetion of indeces.
i[-1] = i[0]

# Sets a scalar argument
# and performs an assignment.
y = -1
x[i] = y

print('index:', i,
      'argument:', y,
      'result:', x,
      sep='\n', end='\n\n')

# Sets an array as an argument
# and performs an assignment.
y = np.arange(i.size)
y = -y
x[i] = y

print('index:', i,
      'argument:', y,
      'result:', x,
      sep='\n')

target:
[0 1 2 3 4 5 6 7 8 9]

index:
[2 8 4 2]
argument:
-1
result:
[ 0  1 -1  3 -1  5  6  7 -1  9]

index:
[2 8 4 2]
argument:
[ 0 -1 -2 -3]
result:
[ 0  1 -3  3 -2  5  6  7 -1  9]


### Incremention

In [4]:
# Creates 1D array,
# which is a target to increment to.
x_size = 10
x = np.arange(x_size)

print('target:', x,
      sep = '\n', end='\n\n')

# Creates 1D array of integers,
# which is an array of indeces.
i_low, i_high = 0, x.size
i_size = 4
i = np.random.randint(low=i_low, high=i_high,
                      size=i_size)
# Stupid way to provide
# a repetion of indeces.
i[-1] = i[0]

# Sets a scalar argument
# and performs an incremention.
y = 1
x[i] += y

print('index:', i,
      'argument:', y,
      'result:', x,
      sep='\n', end='\n\n')

# Sets an array as an argument
# and performs an incremention.
y = np.arange(i.size)
x[i] += y

print('index:', i,
      'argument:', y,
      'result:', x,
      sep='\n')

target:
[0 1 2 3 4 5 6 7 8 9]

index:
[6 4 8 6]
argument:
1
result:
[0 1 2 3 5 5 7 7 9 9]

index:
[6 4 8 6]
argument:
[0 1 2 3]
result:
[ 0  1  2  3  6  5 10  7 11  9]
