# Indexing with Boolean Arrays


## Indexing by Boolean Arrays of the Same Shape

* When we index arrays with boolean indices,
  we explicitly choose
  which items in the array
  we want and which ones we don’t.
* The most natural way one can think of for boolean indexing
  is to use boolean arrays
  that have the same shape as the original array.
  This property can be very useful in assignments.

In [1]:
import numpy as np

### 1D Array Indexing

In [2]:
# Creates 1D array of random integers.
x_low, x_high = 1, 12 + 1
x_size = 12
x = np.random.randint(low=x_low, high=x_high,
                      size = x_size)
print('array:', x, sep='\n')

# Sets a scalar for compare condition.
y = 6
# Creates 1D array of booleans
# corresponding to condition.
b = x > y
print(f'higher: {y}',
      'corresponded:', b,
      sep='\n')

# Creates 1D array of integers
# with the selected elements
# corresponding to condition.
z = x[b]
print('selected:', z, sep='\n')

# Modifies 1D array
# by incrementing the selected elements.
if z.size > 0:
    x[b] += y - z
print('incremented:', x, sep='\n')

# Modifies 1D array
# by assignment the selected elements.
x[b] = 0
print('assigned:', x, sep='\n')

array:
[ 1 11  9  1  7  7  6  5  8  6  9  3]
higher: 6
corresponded:
[False  True  True False  True  True False False  True False  True False]
selected:
[11  9  7  7  8  9]
incremented:
[1 6 6 1 6 6 6 5 6 6 6 3]
assigned:
[1 0 0 1 0 0 6 5 0 6 0 3]


### 2D Array Indexing

In [3]:
# Creates 2D array of random integers.
x_shape = 3, 4
x_low, x_high = 1, x_shape[0] * x_shape[1] + 1
x = np.random.randint(low=x_low, high=x_high,
                      size = x_shape)
print('array:', x, sep='\n')

# Sets a scalar for compare condition.
y = 6
# Creates 2D array of booleans
# corresponding to condition.
b = x < y
print(f'below: {y}',
      'corresponded:', b,
      sep='\n')

# Creates 2D array of integers
# with the selected elements
# corresponding to condition.
z = x[b]
print('selected:', z, sep='\n')

# Modifies 2D array
# by incrementing the selected elements.
if z.size > 0:
    x[b] += y - z
print('incremented:', x, sep='\n')

# Modifies 2D array
# by assignment the selected elements.
x[b] = 0
print('assigned:', x, sep='\n')

array:
[[ 4  9  6 10]
 [10  3  4  9]
 [ 5  4  2  7]]
below: 6
corresponded:
[[ True False False False]
 [False  True  True False]
 [ True  True  True False]]
selected:
[4 3 4 5 4 2]
incremented:
[[ 6  9  6 10]
 [10  6  6  9]
 [ 6  6  6  7]]
assigned:
[[ 0  9  6 10]
 [10  0  0  9]
 [ 0  0  0  7]]
