# Indexing with Boolean Arrays

When we index arrays with boolean indices,
we explicitly choose
which items in the array we want
and which ones we don’t.


## Indexing by 1D Boolean Arrays

* Another way of indexing with booleans
  is more similar to integer indexing:
  for each dimension of the array
  we give a 1D boolean array
  selecting the slices we want.
* Note that
  the length of the 1D boolean array must coincide
  with the length of the dimension (or axis)
  you want to slice.

In [1]:
import numpy as np

In [2]:
# Creates 2D array of integers.
x_shape = 3, 4
x_step = 1
x_start = 1
x_stop = x_start + \
         x_shape[0] * x_shape[1] * x_step
x = np.arange(start=x_start, stop=x_stop,
              step=x_step)
x.shape = x_shape

# Creates a tuple of two 1D arrays
# of random booleans
# with sizes being equal to lengths
# of corresponding axes of 2D array.
# That is actually
# first and second dimension selection.
b = (np.random.randint(low=0, high=2,
                       size=x.shape[0]) == 1,
     np.random.randint(low=0, high=2,
                       size=x.shape[1]) == 1)

print('array:', x,
      f'shape: {x.shape}\n',

      'row index:', b[0],
      f'size: {b[0].size}',
      f'any: {np.any(b[0])}\n',

      'column index:', b[1],
      f'size: {b[1].size}',
      f'any: {np.any(b[1])}',
      sep='\n')

array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4)

row index:
[ True False False]
size: 3
any: True

column index:
[ True  True False  True]
size: 4
any: True


In [3]:
# Selecting rows.

print('array:', x,
      '\nrow index:', b[0],
      sep='\n')

if np.any(b[0]):
    print('\nselected rows:\n', x[b[0],:])  # selecting rows

array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

row index:
[ True False False]

selected rows:
 [[1 2 3 4]]


In [4]:
# Selecting columns.

print('array:', x,
      '\ncolumn index:', b[1],
      sep='\n')

if np.any(b[1]):
    print('\nselected rows:\n',
          x[:,b[1]])  # selecting columns

array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

column index:
[ True  True False  True]

selected rows:
 [[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [5]:
# Selecting the both rows and columns.

print('array:', x,
      '\nrow index:', b[0],
      '\ncolumn index:', b[1],
      sep='\n')

if np.any(b[0]) and np.any(b[1]):
    print('\nselected:\n',
          x[b[0], b[1]])

array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

row index:
[ True False False]

column index:
[ True  True False  True]

selected:
 [1 2 4]
