# The ix_() function

In [1]:
import numpy as np

In [2]:
# Creates three 1D arraies
# of different size.
x = np.array([0, 1, 2])
y = np.array([0, 1, 2, 3])
z = np.array([0, 1, 2, 3, 4])

print('x:', x, 
      'size: {}\n'.format(x.size),
      'y:', y, 
      'size: {}\n'.format(y.size),
      'z:', z,
      'size: {}'.format(z.size),
      sep='\n')

x:
[0 1 2]
size: 3

y:
[0 1 2 3]
size: 4

z:
[0 1 2 3 4]
size: 5


### 2D

In [3]:
# Creates two 2D arraies
# being suitable for broadcasting.

# Increases array dimension
# by adding second axis
# using newaxis object.
x1 = x[:, np.newaxis]
# Which can be done using
# reshape function.
# x1 = np.reshape(x, (-1, 1))

# Increases array dimension
# by adding firts axis
# using newaxis object.
y1 = y[np.newaxis, :]
# Which can be done using
# reshape function.
# y1 = np.reshape(y, (1, -1))

# The same can be made
# using ix_ funcyion.
x2, y2 = np.ix_(x, y)

# Applies elementwise operations
# using broadcasting.
f1 = x1 + y1
f2 = x2 + y2

print('x:', x, 
      'x1:', x1,
      'check: {}\n'.format(np.all(x1 == x2)),
      'y:', y, 
      'y1:', y1, 
      'check: {}\n'.format(np.all(y1 == y2)),
      'f1:', f1, 
      'check: {}'.format(np.all(f1 == f2)),
      sep='\n')

x:
[0 1 2]
x1:
[[0]
 [1]
 [2]]
check: True

y:
[0 1 2 3]
y1:
[[0 1 2 3]]
check: True

f1:
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
check: True


### 3D

In [4]:
# Creates two 2D arraies
# being suitable for broadcasting.

# Increases array dimension
# by adding second axis
# using newaxis object.
x1 = x[:, np.newaxis, np.newaxis]
# Which can be done using
# reshape function.
# x1 = np.reshape(x, (-1, 1, 1))

# Increases array dimension
# by adding firts axis
# using newaxis object.
y1 = y[np.newaxis, :, np.newaxis]
# Which can be done using
# reshape function.
# y1 = np.reshape(y, (1, -1, 1))

# Increases array dimension
# by adding firts axis
# using newaxis object.
z1 = z[np.newaxis, np.newaxis, :]
# Which can be done using
# reshape function.
# z1 = np.reshape(z, (1, 1, -1))


# The same can be made
# using ix_ funcyion.
x2, y2, z2 = np.ix_(x, y, z)

# Applies elementwise operations
# using broadcasting.
f1 = x1 + y1 + z1
f2 = x2 + y2 + z2

print('x:', x, 
      'x1:', x1,
      'check: {}\n'.format(np.all(x1 == x2)),
      'y:', y, 
      'y1:', y1, 
      'check: {}\n'.format(np.all(y1 == y2)),
      'z:', z, 
      'z1:', z1, 
      'check: {}\n'.format(np.all(z1 == z2)),
      'f1:', f1, 
      'check: {}'.format(np.all(f1 == f2)),
      sep='\n')

x:
[0 1 2]
x1:
[[[0]]

 [[1]]

 [[2]]]
check: True

y:
[0 1 2 3]
y1:
[[[0]
  [1]
  [2]
  [3]]]
check: True

z:
[0 1 2 3 4]
z1:
[[[0 1 2 3 4]]]
check: True

f1:
[[[0 1 2 3 4]
  [1 2 3 4 5]
  [2 3 4 5 6]
  [3 4 5 6 7]]

 [[1 2 3 4 5]
  [2 3 4 5 6]
  [3 4 5 6 7]
  [4 5 6 7 8]]

 [[2 3 4 5 6]
  [3 4 5 6 7]
  [4 5 6 7 8]
  [5 6 7 8 9]]]
check: True
